### ISSUE TITLE
Preroll ads not being blocked 

### ISSUE THREAD

**Issue by TheInverseKey** [younesaassila/ttv-lol-pro#100]
Ads now are no longer being blocked when navigating to a channel.

**Comment by younesaassila** [comment]
Try to use another proxy (see suggestions here: #37)

**Comment by MisterSheeple** [comment]
The TTV LOL API seems to be down right now. Luminous is working fine for me though.

**Comment by MisterSheeple** [comment]
Seems to be back up now.

**Comment by younesaassila** [comment]
Closing this since it is a proxy issue and not an extension one.
