### ISSUE TITLE
Low quality when switching tabs

### ISSUE THREAD

**Issue by CharisardTT** [younesaassila/ttv-lol-pro#105]
I don't know if it is a bug, but when I switch tab on Edge the stream quality drops to 360p or it pauses for a few seconds.

When I switch back to the stream tab, it recovers the 1080p quality after a second and I don't have it on Auto: https://i.imgur.com/Cspivx2.png

This doesn't happen if I turn off the extension, so...?

**Comment by younesaassila** [comment]
Do you use the VAFT or Video-Swap-New script? Because the way they stop ads is by replacing the video feed by the mini-player feed (lower quality) when an ad is playing. Could be related to that.

TTV LOL PRO doesn't mess with the qualities at all.

**Comment by CharisardTT** [comment]
Oh you mean the script used in Ublock, I see. Yeah that was the problem, thanks a lot 👍

**Comment by CharisardTT** [comment]
Sorry but I've just tested more and even without the VAFT, the quality still changes when switching tabs. 

I also tested it in Chrome and is happens as well. I can't figure out what is causing it 🤔

**Comment by llaurenss** [comment]
That doesn't have anything to do with this extension. Twitch lowers the quality when you're not actively watching to save bandwidth on their servers, you can use something like this to prevent that from happening https://chrome.google.com/webstore/detail/always-active-window-alwa/ehllkhjndgnlokhomdlhgbineffifcbj?hl=en

**Comment by CharisardTT** [comment]
But the problem is that if I disable ttv lol pro, the quality will always stay at 1080p, even switching tabs. So I feel like it's not a twitch problem.

I'll still try those extensions to fix it for now, thanks

**Comment by CharisardTT** [comment]
Yeah I've tried the first extension and it fixed the issue. 

Also, I've asked some friends to check if they have the same problem as me, and they do, even using different browsers like Chrome or Mozilla.

**Comment by younesaassila** [comment]
Great! Yeah unfortunately I don't think anything can be done about this. Twitch is trying to save bandwidth when you're playing a stream in the background.

**Comment by eldepor** [comment]
I think its a great feature tho, specially for ppl using low end computers like me.
