### ISSUE TITLE
Chromium, deprecated manifest version

### ISSUE THREAD

**Issue by uliminati** [younesaassila/ttv-lol-pro#106]
Chromium, SRWare Iron 110.0.5600.0

Loading folder from unpacked zip file shows TTV LOL PRO 1.8.1 in the extensions menu, but with two errors

Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

Unrecognized manifest key 'browser_specific_settings'.

**Comment by Ashesh3** [comment]
@younesaassila This would be really helpful, I'd like to publish this on chrome web store and Microsoft edge store (with credits to this Repo). Both of them require manifest v3.
