### ISSUE TITLE
When dragging the urls in the proxy list it doesn't include the https://

### ISSUE THREAD

**Issue by thinkpad4** [younesaassila/ttv-lol-pro#113]
@younesaassila In the new version 1.9.0 the dragging feature for moving different proxies to be the primary one doesn't move the https:// with it.  So it those a error saying blahblah is not a valid url.  Example moving https://as.luminous.dev to the top results in just as.luminous.dev moving.  

Thank you very much

**Comment by thinkpad4** [comment]
Please ignore, I think I made a derp

**Comment by younesaassila** [comment]
I didn't code any dragging feature. Does the browser provide one by default? 😲

**Comment by thinkpad4** [comment]
I'm using Chrome, when I saw the new version I thought you added the drag feature without reading the changelog first, that was my derp.  I think it's just the native drag and drop in chrome like when you highlight a word you can click and drag it, Chrome must see the boxes for the proxies as pre highlighted allowing me to just click on the url and drag it, it just doesn't keep the https:// when dropping it in to a empty box
