### ISSUE TITLE
[Suggestion] Option to sort Proxies

### ISSUE THREAD

**Issue by juliocoliveira** [younesaassila/ttv-lol-pro#115]
Would be great a option to sort proxies, Click on Arrows (Up/Down) to change the order of the proxy, and/or click and drag the field to change the order.

Today if you have a lot of proxies to change the order you have to remove all, and add all again in the correct order, or export settings and edit file, change the order and then import the settings backup file.

**Comment by younesaassila** [comment]
Thanks for the issue! Closing it down since there's already a similar issue (#92) but don't worry the idea is great :)

**Comment by juliocoliveira** [comment]
Oh, I see, Didn't saw that issue. Thanks!
