### ISSUE TITLE
Streams not loading

### ISSUE THREAD

**Issue by Lucas559-noob** [younesaassila/ttv-lol-pro#117]
This issue started today, when I go on a stream, it doesn't load, it keeps loading and nothing happens, I need to disable or reload the extension to stream start.
Clicking on extension it doesn't open either, not even on settings right-clicking on it.
Looking at errors, I saw some errors.
![image](https://user-images.githubusercontent.com/54007604/232238831-83b96474-116e-4c36-bf22-7f7b9e97d855.png)
![image](https://user-images.githubusercontent.com/54007604/232238860-d00ece27-8564-4f24-afdb-484deabd01fd.png)
![image](https://user-images.githubusercontent.com/54007604/232238872-0b5bf810-88bb-452b-b589-dab76d9d1810.png)
![image](https://user-images.githubusercontent.com/54007604/232238884-844e9f78-1fdb-4bf0-8efa-e11660b53018.png)
Not sure if they are related to my current issues.

**Comment by younesaassila** [comment]
Does using another proxy as the primary (like the TTV LOL API) solve some issues?

**Comment by Lucas559-noob** [comment]
well now everything is back to normal, not sure why the UI and settings did not opened(took a long time to open), now it opened the settings under 10 seconds and then opened the UI of extension, not sure what caused it to take time to open.
 Extensions don't require connection with a server to fully open, right? I would say that could be the reason, but at same time it doesn't make sense.
