### ISSUE TITLE
An ad slipped when a stream loaded

### ISSUE THREAD

**Issue by Lucas559-noob** [younesaassila/ttv-lol-pro#119]
So the streamer ended a stream with problem on OBS, he probably restarted OBS and opened the stream again, it did not autoplay, when I clicked to resume, it loaded an ad, looking at the extension it say is working. Also the ad was not for my location.
![image](https://user-images.githubusercontent.com/54007604/232942781-867582b1-c9b8-4b4e-b83b-94e9250b15ab.png)

**Comment by younesaassila** [comment]
Were you using the Asian proxy?

**Comment by Lucas559-noob** [comment]
> Were you using the Asian proxy?

yeah, sorry for the late response, I was using https://lb-na.perfprod.com I think

**Comment by Terra-B-Welch** [comment]
just had an ad slip myself, proxies might be failing?

**Comment by younesaassila** [comment]
Closing this issue since it is similar to #121 and #121 has more activity. That way the conversation can be kept in a single place.
