### ISSUE TITLE
how to install on macos: This extension is not listed in the Chrome Web Store and may have been added without your knowledge.

### ISSUE THREAD

**Issue by Geczy** [younesaassila/ttv-lol-pro#120]
<img width="702" alt="image" src="https://user-images.githubusercontent.com/1036968/233414841-aa2bb1f4-93d0-4e47-a801-e6bc98430774.png">

**Comment by younesaassila** [comment]
Automatic updates are not supported on macOS. Please use the unpacked version instead.
