### ISSUE TITLE
Certain ads not being blocked as of 4-24-23

### ISSUE THREAD

**Issue by beerninja** [younesaassila/ttv-lol-pro#121]
As of this morning instead of the stream going black for about 5 seconds then coming back, a full 30 second ad plays.  I tried this on two different channels and has the same problem.  The channel would occasionally go black to block ads (normal) but then every once in a while a full 30 second ad would play.

I'm using the latest Firefox, latest ttv lol pro, ublock origin, and video-swap-new (via ublock origin script link)

Thanks

**Comment by younesaassila** [comment]
What exact version of Firefox are you using?
It's possible Twitch now delivers pre-rolls after a player reset, in which case the "Reset player on midroll" would become useless.
Try to use another proxy (see #37). I've read people getting good results with the Asian proxy listed there. This method is more stable.

**Comment by MuhannadRidah** [comment]
Hi , I'm starting to get ads today. I tried the NA/asia proxy. They don't show ads but they are lagging [it will disconnect every 1-2 min ] only eu proxy shows ads. [ when i open the stream for first time and mid-rolls ads ]  I am using Firefox 112.0.1

**Comment by true-curly** [comment]
Hello. Mid stream Ads are getting through occasionally regardless of what proxy is set. I've tried these:
https://as.luminous.dev
https://lb-eu.perfprod.com
https://api.ttv.lol
https://lb-na.perfprod.com
https://eu.luminous.dev/

What happens is the page seems to reload 4-5 times then the ad starts. Firefox, TTV LOL PRO, and uBlock Origin are all up to date.
Seems infrequent so far and I've only seen it on a few channels.

**Comment by jvachez** [comment]
I have seen an ad for Zelda today !

**Comment by TsukiZero** [comment]
Ads have been leaking through lately.

**Comment by younesaassila** [comment]
> Ads have been leaking through lately. And constantly at that.

Please check out the latest v2 beta and let us know how it is working for you!
