### ISSUE TITLE
Manually resetting player shows incorrect stream delay when using extension

### ISSUE THREAD

**Issue by dubbyOW** [younesaassila/ttv-lol-pro#123]
when manually resetting the player with a use of FFZ, stream delay is counted incorrectly

I was testing what is actually happening, I came to a conclusion that stream delay itself when using extension is normal, but the displayed delay is the amount of time, that passed between initial stream player load and the last action of manual player reset

example: start the stream and reset the player manually after 10s, stream delay now says 10s, if you reset the player after lets say another 5s, it will now be 15s

screenshot below shows a delay of 12s, pressed reset player button multiple times, last button press was 12s after initial player load, to display this on your end use FFZ extension, go to settings, Channel -> Metadata -> Playback Statistics ENABLED
![image](https://user-images.githubusercontent.com/119939110/234434355-b1dcc0bd-6e16-4b33-ad37-5f1e01c7c839.png)

if youre wondering why I use reset player button, its because often initial player load comes with a large delay, can be like 8 seconds at times, and I dont want to wait for it to catch up so I reset the player, but it results in this bug

**Comment by Ashesh3** [comment]
@DubbyOW On a side note, how do you get that stream delay stat? I do not see it anywhere on Twitch.

**Comment by dubbyOW** [comment]
> @DubbyOW On a side note, how do you get that stream delay stat? I do not see it anywhere on Twitch.

read what I typed again :) its all there

**Comment by younesaassila** [comment]
v1 is being deprecated since Twitch is slowly patching it. Since this issue is related to v1 only, I'm closing it as won't fix.
