### ISSUE TITLE
Suddenly twitch stream wont start (stucking on loading) with TTV LOL PRO

### ISSUE THREAD

**Issue by anefodiasmenos** [younesaassila/ttv-lol-pro#128]
When i disable it the stream starts perfect
Chrome Windows 11 latest updates.

**Comment by erik9012** [comment]
do you get the same loading issue if you watch the twitch stream on https://twitchls.com/ instead of https://twitch.tv/ ? You can test it with replacing the the twitch.tv domain  with  twitchls.com and keeping whats at the end of the url the same. For example https://twitchls.com/twitch instead of https://www.twitch.tv/twitch

**Comment by anefodiasmenos** [comment]
The same On https://twitchls.com/ Without sign in.

**Comment by anefodiasmenos** [comment]
Now it starts perfect all of a sudden Dunno if its my connect i have fiber 100 Pfff

**Comment by anefodiasmenos** [comment]
As of now that im typing im loading good now.

**Comment by erik9012** [comment]
maybe there could be a update that  ttv lol pro auto prioritzes the fastest proxy checking that once in the 48 hours or something. but i dunno, nice that it works again

**Comment by younesaassila** [comment]
> maybe there could be a update that ttv lol pro auto prioritzes the fastest proxy checking that once in the 48 hours or something. but i dunno, nice that it works again

Yeah I think the best option would be to implement list of proxies just like adblockers using blocklists. That way there would be one default proxy list for everyone that auto updates when the reliability of some proxies change. No need for newcomers to have to mess with proxy settings and find the best one

**Comment by erik9012** [comment]
> Yeah I think the best option would be to implement list of proxies just like adblockers using blocklists. That way there would be one default proxy list for everyone that auto updates when the reliability of some proxies change. No need for newcomers to have to mess with proxy settings and find the best one

I think the Dev said that he will keep ttv.lol domain as default, because it's a fork of their extension and because the project is called ttv lol pro. But if it could be a thing to auto sort on reliability then that would be very useful

**Comment by anefodiasmenos** [comment]
i went and updated to 1.9.1 and it drops some errors.
![chrome_KGEazJMnyZ](https://github.com/younesaassila/ttv-lol-pro/assets/27023691/fe5c6c8e-e07b-439f-8e86-ffa45b341ac5)
![chrome_Klek1xAN0N](https://github.com/younesaassila/ttv-lol-pro/assets/27023691/0ae91cc7-cf9c-4720-a640-b7dce1a5e80e)
![chrome_QopQq5exQG](https://github.com/younesaassila/ttv-lol-pro/assets/27023691/c09c3fdf-b829-4112-98fb-e4d24f693cb4)
![chrome_RRCT4nbtCQ](https://github.com/younesaassila/ttv-lol-pro/assets/27023691/6718ad51-5996-48c9-8e9f-e47b12dd9bf9)
![chrome_TiJ69YhWXF](https://github.com/younesaassila/ttv-lol-pro/assets/27023691/316d700f-8336-4fe5-99ff-cc13b937fda9)

**Comment by anefodiasmenos** [comment]
Even on 1.9.0 it still drops some errors is it normal? even if i follow the instractions

**Comment by ynnniV** [comment]
Now is going good. Maybe issues with proxies?

**Comment by younesaassila** [comment]
> Even on 1.9.0 it still drops some errors is it normal? even if i follow the instractions

There's two warnings that show up after a normal installations - those can be ignored.

**Comment by ynnniV** [comment]
Now i got like 2-3 restart of streaming and showing me the ads.

**Comment by FBI4ever** [comment]
yeah , it seems a proxy issue .... at the moment it is working fine "with some hiccups on fetching the live.m3u8 link as i see it on the browser inspector"

**Comment by ynnniV** [comment]
I tired to use other proxies and is going good.

List of other proxies:
https://lb-eu.perfprod.com (Europe)
https://lb-eu2.perfprod.com (Europe 2)
https://lb-na.perfprod.com (NA) (Proxied to Asia)
https://lb-as.perfprod.com (Asia)

Saw it here: https://github.com/younesaassila/ttv-lol-pro/discussions/37#discussioncomment-5426032

**Comment by DcSensai** [comment]
its doing the same for me. i have the midroll option unchecked and i am using those proxies listed as well.

**Comment by gittar1** [comment]
same thing for me theres times where it works and theres times where it stays on a black loading screen but this is only when i open or refresh a page whenever the video is paused i can start it by pressing play but when i refresh or open a new stream its stuck on loading. i also noticed that the extension is unresponsive or partially unresponsive during these times whenever i try open options when its having issues its just stuck on a loading page and becomes unresponsive prompting me to wait or close it

**Comment by Geczy** [comment]
Same here, i get the "reset player" red button

**Comment by xPixelGhost** [comment]
Having this issue also of the video stuck on infinite buffering but works fine when disabled I'm using brave browser with latest version and using ver 1.9.2 of ttvlol also tried all proxies and sometimes the video would start but then go back a buffering.

**Comment by ghost** [comment]
Remove all custom scripts in ublock origin including vaft script and the other settings.

**Comment by anefodiasmenos** [comment]
Yea its not ublock i have disable it just for twitch and still keeps loading with all 4 lists on 1,9.2
If i whitelist the stream it works
https://lb-eu.perfprod.com/ (Europe) 
https://lb-eu2.perfprod.com/ (Europe 2)
https://lb-na.perfprod.com/ (NA) (Proxied to Asia)
https://lb-as.perfprod.com/ (Asia)

**Comment by anefodiasmenos** [comment]
![chrome_HqiBn1SEVu](https://github.com/younesaassila/ttv-lol-pro/assets/27023691/45992dd3-11c4-4201-8d64-468661c94f66)

**Comment by AgentJohnDoe** [comment]
Can anyone help me to even install these things? When I try to load unpacked extension I just get "Error Manifest file is missing or unreadable".
