### ISSUE TITLE
Will you still work on v1 besides v2?

### ISSUE THREAD

**Issue by thinkpad4** [younesaassila/ttv-lol-pro#132]
@younesaassila Will you continue to maintain v1 besides v2, at least until there are more proxies available for v2?  Or will you get v1 to a stable and reliable state and keep it as legacy, and move your focus to v2?

Thank you very much

**Comment by younesaassila** [comment]
V2 is compatible with any HTTP proxy. I don't think v1 is going to get any further update though, either it works for some people or it doesn't, so yeah ^^

**Comment by thinkpad4** [comment]
Thanks for letting me know
