### ISSUE TITLE
Muting Twitch causes Video to pause

### ISSUE THREAD

**Issue by Ranmaz** [younesaassila/ttv-lol-pro#133]
When I switch back to a twitch tab, it takes a moment for the Video to Load.  To bypass this, I need to not mute the stream, and use the mute tab feature on my Edge web browser instead.

**Comment by younesaassila** [comment]
Does this behavior persist when you disable the extension? I'm pretty convinced this is an optimization done by Twitch. They are known to also drop the quality when a tab is in the background.

**Comment by younesaassila** [comment]
Unfortunately, I am not able to reproduce this bug. Do you have "Reset player on midroll" turned off in TTV LOL PRO options? If not, please do so and report back.

**Comment by younesaassila** [comment]
Ah sorry, I assumed you were using TTV LOL PRO v1. Still cannot reproduce. What country are you watching Twitch from?

**Comment by Ranmaz** [comment]
Canada

**Comment by younesaassila** [comment]
Could you try the America proxy listed in #130 and let me know if the issue persists

**Comment by Ranmaz** [comment]
> 

america.ttvlolpro.perfprod.com:8014  Do I move this to the number 1 spot?

**Comment by younesaassila** [comment]
Yes put it as Primary

**Comment by Ranmaz** [comment]
Same behavior.  Although it loads faster.  It's still very clear though, that when I have the stream sound on, and mute the tab, and switch back and forth between tabs, I return to where the stream was playing, and no stutter or re-loading.

Can I attach a video here? if not, i can link it to a youtube link.

**Comment by younesaassila** [comment]
Sure, a video could be helpful. GitHub lets you attach files, though I'm not sure what the size limit is and if a video would fit.

**Comment by Ranmaz** [comment]
It was too big, so I had to upload it to youtube instead https://youtu.be/qcBItWCnNqQ

**Comment by Ranmaz** [comment]
ok youtube is not processing it.  I uploaded it to dailymotion:

https://dai.ly/k57NCJbCSCKX3iz7TXz

**Comment by Undead-Tech** [comment]
This doesn't happen on brave but I am able to reproduce this on chrome. I can't test edge since I use a custom windows install that doesn't include it. If I find a way to fix it completely I'll post; however, I will add deleting site data and resetting site permissions for twitch fixes it until you close the tab or reload the site in any way. Switching to other streams or going anywhere else on the site is fine until you reload or close the tab.

**Comment by Undead-Tech** [comment]
So I have figured out that if the tab loads with the player already muted from a previous session it will do this. Unmuting the player and muting it again fixes it.

When inspecting the tab while this happens something from "player-core-variant-b-2c0fc18568332fa5dad8.js" is used. 
![test](https://github.com/younesaassila/ttv-lol-pro/assets/71444960/601d3de9-7ce8-4a36-a59f-78ff62b96f0d)

**Comment by Ranmaz** [comment]
> So I have figured out that if the tab loads with the player already muted from a previous session it will do this. Unmuting the player and muting it again fixes it.
> 
> When inspecting the tab while this happens something from "player-core-variant-b-2c0fc18568332fa5dad8.js" is used. While I want to I don't know how to code currently so idk what else I could do to help. Hope this helps out. ![test](https://user-images.githubusercontent.com/71444960/239148263-601d3de9-7ce8-4a36-a59f-78ff62b96f0d.png)

This is great!  I can easily do that, but it would be nice if this can be fixed with the code.  I can technically remind myself to do this, but it would be nice that this can be resolved without me having to unmuting and muting it again.

**Comment by younesaassila** [comment]
Still can't reproduce on Chrome. Though from what I can see from your video, the stream still plays fine after the few 100s milliseconds of loading. I still believe this is just Twitch doing some bandwidth savings and having to quick reload the stream on tab re-focus.
I'll let the issue open a bit to see if other people can reproduce and debug what's happening network-wise

**Comment by younesaassila** [comment]
No problem, thanks! By reporting issues we all learn something new!
