### ISSUE TITLE
Beta report: Still seeing ads even in Whopper mode.

### ISSUE THREAD

**Issue by DaveKap** [younesaassila/ttv-lol-pro#134]
Just letting you know that I only have the 2 default proxies with Whopper mode on and I'm still seeing ads when starting a stream. Unfortunately, the beta doesn't have a display telling me whether or not it can contact the proxies, which the stable version current has and has been letting me know that, lately, the proxies have been unconnectable. These proxies being down is what led me to try the beta. Unfortunately, it is not yet the solution we need.

**Comment by younesaassila** [comment]
Make sure you have no other Twitch ad blocker running, that you've cleared your browser's cache. Did the extension not work without Whopper mode? (What's the reason you enabled it?)
At last if that doesn't work try one of the beta proxies listed in #130

**Comment by laichiaheng** [comment]
@younesaassila Does Ublock Origin count?

**Comment by younesaassila** [comment]
> @younesaassila Does Ublock Origin count?

No, uBlock is a general purpose ad blocker, so it's fine, even recommended.

**Comment by DaveKap** [comment]
As far as I can tell, it's the only one I'm using. I'll try the two other proxies in #130 without and with Whopper mode and report back.

**Comment by DaveKap** [comment]
Whopper mode off, other two proxies added, things are working better!
