### ISSUE TITLE
Cant change dns because of "Managed by your organization" noti

### ISSUE THREAD

**Issue by likeyeeah** [younesaassila/ttv-lol-pro#140]
I live in Turkey. The goverment here blocks everything that they dont like. Porn is blocked, wiki was blocked 2 years ago, before that youtube was blocked for 2 whole years. So i need to use dns. I normally use chromes dns changing thing but i cant use it because it says "Managed by your organization". Using windows' dns changer doesnt help too. I really dont like using vpns. Please help me with this

**Comment by younesaassila** [comment]
Use the TTV LOL PRO version without automatic updates (ZIP file).
To remove the management policy, download the allowlist.zip file in the latest release, then go in allowlist > unallow and execute the file for your browser.
