### ISSUE TITLE
Did not block this time

### ISSUE THREAD

**Issue by Lucas559-noob** [younesaassila/ttv-lol-pro#141]
Was running v2 on default settings, stream reloaded and after 3 seconds, started an ad(that wasn't shown), reloaded page to see and same thing again, enabled whopper and reloaded, same thing again, I guess it sometimes doesn't connect to proxy.
![image](https://github.com/younesaassila/ttv-lol-pro/assets/54007604/43bc8cbe-fa2b-4625-a085-fb7acd3b6952)

**Comment by Lucas559-noob** [comment]
Maybe this was caused by video-swap-new, forgot to disable

**Comment by younesaassila** [comment]
Yes please disable video-swap-new. Also feedback about v2 is here: #131
