### ISSUE TITLE
just seeing 

### ISSUE THREAD

**Issue by ItsBluey** [younesaassila/ttv-lol-pro#144]
i click on a stream it starts buttering then restarts player over and over again or sometimes its just black screen or the purple page 
![image](https://github.com/younesaassila/ttv-lol-pro/assets/20117258/2bd70872-60aa-438f-9676-9c0b720e3ca5)

**Comment by younesaassila** [comment]
Are you using the latest v1.9.2 version?
Also you're seeing ads because no proxy responded to the extension's ping. Check out #37 for other proxies.

**Comment by ItsBluey** [comment]
thanks using beta
