### ISSUE TITLE
After enabling it the "Update hint" it does not disable. 

### ISSUE THREAD

**Issue by juliocoliveira** [younesaassila/ttv-lol-pro#145]
![image](https://github.com/younesaassila/ttv-lol-pro/assets/6606725/0e2e5405-50cc-46a0-91a6-f69ec9cfce45)
v1.9.2

**Comment by juliocoliveira** [comment]
Managed to get rid of it by reseting it to default settings.

**Comment by ghost** [comment]
Reboot your browser to finalize changes (also: **Disable the first option** as that breaks FrankerFaceZ!!!)

**Comment by younesaassila** [comment]
@juliocoliveira I think you have indeed found a bug. Upgrade process doesn't clear the update flag. Did you attempt to restart your browser? That should have fixed it.
Thanks for the report!

**Comment by younesaassila** [comment]
Also just to make sure, are you using the XPI version or the unpacked one?

**Comment by juliocoliveira** [comment]
XPI

**Comment by younesaassila** [comment]
Thanks, fixed the bug
