### ISSUE TITLE
Error #2000, There was a network error. Please try again.

### ISSUE THREAD

**Issue by Goofyd00d** [younesaassila/ttv-lol-pro#153]
Was just fine earlier today. Works fine when extension is disabled. Cycled through making all approved proxies primary. Disabling Ublock did nothing.

**Comment by younesaassila** [comment]
All v1 proxies are broken. Twitch changed something with their API.

**Comment by juliocoliveira** [comment]
If you are using V1, use the latest v1.9.2, And use https://eu2.luminous.dev or https://eu.luminous.dev as proxy it is working just fine for me.
