### ISSUE TITLE
All server pings failed

### ISSUE THREAD

**Issue by Anony400** [younesaassila/ttv-lol-pro#154]
Using latest Chrome browser version, Windows 10.

Tried a couple channels with 1.9.2 & then later with 2.0.0.5 beta 5

I get two ads when I click on a stream (about 14 seconds long). 

Is there any way for me to fix "All server pings failed" message?

**Comment by younesaassila** [comment]
Closing since there's already 2 open issues about this Twitch change.
Also beta 5 should no longer be used since the default proxies for it have been shut down.
