### ISSUE TITLE
2.0 beta.8 

### ISSUE THREAD

**Issue by Teraisu** [younesaassila/ttv-lol-pro#155]
when trying to add the add-on its saying that its corrupt? ive tried both fire fox dev and original and doesnt let me apply the add-on

**Comment by juliocoliveira** [comment]
Load the extension on debug section, not standard addons page: about:debugging#/runtime/this-firefox

**Comment by revunix** [comment]
Why can't you use the proxies for Chrome?

**Comment by Teraisu** [comment]
> Load the extension on debug section, not standard addons page: about:debugging#/runtime/this-firefox

do i need to keep applying the extension everytime i restart the browser ?, its working by the way.

**Comment by juliocoliveira** [comment]
> > Load the extension on debug section, not standard addons page: about:debugging#/runtime/this-firefox
> 
> do i need to keep applying the extension everytime i restart the browser ?, its working by the way.

For standard release of Firefox for now YES, you must, if you are on Nightly or ESR or Dev version you have to disable the signature on about:config change the xpinstall.signatures.required to false. This is described on the readme / homepage.  So you can install it as standard addon and it loads normally on each startup.

That is until the extension is fully released and shipped on addon stores then you don't have to do that.

**Comment by Teraisu** [comment]
Thank you !Sent from my Galaxy
-------- Original message --------From: "Júlio C. Oliveira" ***@***.***> Date: 6/1/23  14:15  (GMT-05:00) To: younesaassila/ttv-lol-pro ***@***.***> Cc: Teraisu ***@***.***>, Author ***@***.***> Subject: Re: [younesaassila/ttv-lol-pro] 2.0 beta.8  (Issue #155) 


Load the extension on debug section, not standard addons page: about:debugging#/runtime/this-firefox

do i need to keep applying the extension everytime i restart the browser ?, its working by the way.

For standard release for now YES, you must, if you are on Nightly or ESR or Dev version you have to disable the signature on configs: xpinstall.signatures.required change to false. This is described on the readme / homepage.  So you can install it as standard addon and it loads normally on each release.
That is until the extension is fully released and shipped on addon stores then you don't have to do that.

**Comment by Teraisu** [comment]
Thank you

**Comment by Teraisu** [comment]
> > > Load the extension on debug section, not standard addons page: about:debugging#/runtime/this-firefox
> > 
> > do i need to keep applying the extension everytime i restart the browser ?, its working by the way.
> 
> For standard release of Firefox for now YES, you must, if you are on Nightly or ESR or Dev version you have to disable the signature on about:config change the xpinstall.signatures.required to false. This is described on the readme / homepage.  So you can install it as standard addon and it loads normally on each startup.
> 
> That is until the extension is fully released and shipped on addon stores then you don't have to do that.

The temporary one works for me with an original browser. However, the dev browser, when applying the required to false it doesn't work. I've gone into the extension tab and installed the add-on from file, and it gives me a corrupted prompt when selecting the manifest.json.

**Comment by juliocoliveira** [comment]
> > > > Load the extension on debug section, not standard addons page: about:debugging#/runtime/this-firefox
> > > 
> > > 
> > > do i need to keep applying the extension everytime i restart the browser ?, its working by the way.
> > 
> > 
> > For standard release of Firefox for now YES, you must, if you are on Nightly or ESR or Dev version you have to disable the signature on about:config change the xpinstall.signatures.required to false. This is described on the readme / homepage.  So you can install it as standard addon and it loads normally on each startup.
> > That is until the extension is fully released and shipped on addon stores then you don't have to do that.
> 
> The temporary one works for me with an original browser. However, the dev browser, when applying the required to false it doesn't work. I've gone into the extension tab and installed the add-on from file, and it gives me a corrupted prompt when selecting the manifest.json.

Because is not to select the manifest.json its the whole release zip.

**Comment by Teraisu** [comment]
Okay , thanks !
