### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ItsBluey** [younesaassila/ttv-lol-pro#156]
i am trying to v2 on firefox but it keeps removing the extension after i close firefox 
ive done the " about:config > Set xpinstall.signatures.required to false" but when i get the this step Extensions page > Gear > Install Add-on From File i get this 
![image](https://github.com/younesaassila/ttv-lol-pro/assets/20117258/ea31f70d-5e59-444c-8091-69bafc104554)

**Comment by ItsBluey** [comment]
I Figured it out

**Comment by ItsBluey** [comment]
sorry i didnt read it all

**Comment by girth211** [comment]
care to explain what you did? I read it all and it still gives me that msg.

**Comment by ItsBluey** [comment]
> care to explain what you did? I read it all and it still gives me that msg.

you need to install [firefox](https://www.mozilla.org/en-US/firefox/developer/) dev build  it wont work on normal version

**Comment by girth211** [comment]
> > care to explain what you did? I read it all and it still gives me that msg.
> 
> you need to install [firefox](https://www.mozilla.org/en-US/firefox/developer/) dev build it wont work on normal version

I see, thanks alot!

**Comment by fletchej** [comment]
> > > care to explain what you did? I read it all and it still gives me that msg.
> > 
> > 
> > you need to install [firefox](https://www.mozilla.org/en-US/firefox/developer/) dev build it wont work on normal version
> 
> I see, thanks alot!

I'm getting a message saying the add-on is corrupt when loading from a .zip file. Is that how y'all installed?

**Comment by AgentJohnDoe** [comment]
Can anyone help me to even install these things? When I try to load unpacked extension I just get "Error Manifest file is missing or unreadable".

**Comment by nilaprasad** [comment]
> Can anyone help me to even install these things? When I try to load unpacked extension I just get "Error Manifest file is missing or unreadable".

Follow the instructions here: https://github.com/younesaassila/ttv-lol-pro#installation

Be sure you clear your cache after.

**Comment by AgentJohnDoe** [comment]
> > Can anyone help me to even install these things? When I try to load unpacked extension I just get "Error Manifest file is missing or unreadable".
> 
> Follow the instructions here: https://github.com/younesaassila/ttv-lol-pro#installation
> 
> Be sure you clear your cache after.

There's literally no instructions beyond unzip and click load unpacked. I need the exact file to unpack, which I can't find when downloading the zip from Code>Download ZIP.

**Comment by younesaassila** [comment]
@Piskemannen 
> Download the version for your browser under the "Assets" section of the [latest release](https://github.com/younesaassila/ttv-lol-pro/releases).

Code > Download ZIP is the wrong link

**Comment by nilaprasad** [comment]
> > > Can anyone help me to even install these things? When I try to load unpacked extension I just get "Error Manifest file is missing or unreadable".
> > 
> > 
> > Follow the instructions here: https://github.com/younesaassila/ttv-lol-pro#installation
> > Be sure you clear your cache after.
> 
> There's literally no instructions beyond unzip and click load unpacked. I need the exact file to unpack, which I can't find when downloading the zip from Code>Download ZIP.

I assume you're on Chrome. Download the ZIP from here: https://github.com/younesaassila/ttv-lol-pro/releases/tag/v2.0.0-rc. Should be called CHROMIUM-ttvlolpro-v2.0.0.zip. Then follow the instructions in the installation link I sent before.

**Comment by AgentJohnDoe** [comment]
> > > > Can anyone help me to even install these things? When I try to load unpacked extension I just get "Error Manifest file is missing or unreadable".
> > > 
> > > 
> > > Follow the instructions here: https://github.com/younesaassila/ttv-lol-pro#installation
> > > Be sure you clear your cache after.
> > 
> > 
> > There's literally no instructions beyond unzip and click load unpacked. I need the exact file to unpack, which I can't find when downloading the zip from Code>Download ZIP.
> 
> I assume you're on Chrome. Download the ZIP from here: https://github.com/younesaassila/ttv-lol-pro/releases/tag/v2.0.0-rc. Should be called CHROMIUM-ttvlolpro-v2.0.0.zip. Then follow the instructions in the installation link I sent before.

Tried that, and I'm just supposed to choose the main folder to unpack or? It just unzips a bunch of files to my desktop, and none of them I can select to unpack, just folders.

**Comment by juliocoliveira** [comment]
> > > > > Can anyone help me to even install these things? When I try to load unpacked extension I just get "Error Manifest file is missing or unreadable".
> > > > 
> > > > 
> > > > Follow the instructions here: https://github.com/younesaassila/ttv-lol-pro#installation
> > > > Be sure you clear your cache after.
> > > 
> > > 
> > > There's literally no instructions beyond unzip and click load unpacked. I need the exact file to unpack, which I can't find when downloading the zip from Code>Download ZIP.
> > 
> > 
> > I assume you're on Chrome. Download the ZIP from here: https://github.com/younesaassila/ttv-lol-pro/releases/tag/v2.0.0-rc. Should be called CHROMIUM-ttvlolpro-v2.0.0.zip. Then follow the instructions in the installation link I sent before.
> 
> Tried that, and I'm just supposed to choose the main folder to unpack or? It just unzips a bunch of files to my desktop, and none of them I can select to unpack, just folders.

Uzip the files into a folder, and select the folder to load. Not a file.

**Comment by juliocoliveira** [comment]
The xpinstall.signatures.required trick just works if you are using the Developer or Nightly or ESR version of firefox.
If you are on standard firefox you need to use the Debug Section go to:
```
about:debugging#/runtime/this-firefox
```

And load as a temporary addon.
For now you need to do this every time you open firefox if you are using the standard firefox.

If you are using chrome you need to unzip the file into a folder and load that folder.
But if you are on chrome you need provide your own proxies, firefox extension's default proxy is not accepted.
