### ISSUE TITLE
[Suggestion] Better Indication that the v2 extension is working

### ISSUE THREAD

**Issue by juliocoliveira** [younesaassila/ttv-lol-pro#157]
For me a Red Icon with the text "Not Proxied" means that is NOT working.
But the ads are not showing up, So it's working!.
Can you change it to give a better indication that is working or not, This way it is not very clear.
![image](https://github.com/younesaassila/ttv-lol-pro/assets/6606725/58873d0b-ec09-4263-a924-16a3fe79d71f)

**Comment by younesaassila** [comment]
I might change the red color to a light gray

**Comment by juliocoliveira** [comment]
For a second on the start of the stream it shows that is working:
![image](https://github.com/younesaassila/ttv-lol-pro/assets/6606725/ff635bc9-beb6-4073-aa40-d27626162ebe)
Then it shows the message+red icon that for me means it's not working:
![image](https://github.com/younesaassila/ttv-lol-pro/assets/6606725/1ab12ded-bf3d-42d7-936f-d6196fd9536d)

**Comment by younesaassila** [comment]
Tweaked the design a bit

![image](https://github.com/younesaassila/ttv-lol-pro/assets/47226184/41d81ba4-9f6a-4586-96ed-1edba6f60fca)

**Comment by thinkpad4** [comment]
@younesaassila I like the Green for actively blocking, grey for standby mode, and red for issue, down, not working, etc.
