### ISSUE TITLE
Lightweight program based on Firefox for this extension

### ISSUE THREAD

**Issue by Lucas559-noob** [younesaassila/ttv-lol-pro#162]
**Is your feature request related to a problem? Please describe.**
I started using Firefox, but for some reason it sometimes freezes or has a poor performance. It would be better to have a piece of Firefox (like a fork) for Twitch.

**Describe the solution you'd like**
A lightweight Firefox alternative, or a program/launcher based on the browser for watching Twitch livestreams with TTV LOL PRO.

**Describe alternatives you've considered**
Suggestions for lightweight Firefox forks just for twitch.

**Comment by rwbonesy** [comment]
I'm not a part of this project, just an observer, but I feel like it's well outside of scope for this project.

**Comment by younesaassila** [comment]
Wow yeah this is really out of scope. Developing browsers is hard!
