### ISSUE TITLE
TTV-LOL-PRO broke twitch website

### ISSUE THREAD

**Issue by Gato-soviet** [younesaassila/ttv-lol-pro#166]
In the exactly moment I install TTV-LOL-PRO twitch.tv doenst work anymore. The website show an error "Your browser isnt supported" There's a way to solve it?

**Comment by younesaassila** [comment]
Are you using Kaspersky anti virus?

**Comment by Gato-soviet** [comment]
> Are you using Kaspersky anti virus?

Yes, why?

**Comment by younesaassila** [comment]
Known bug with Kaspersky's "script injection" option. See #167 
Closing this issue to avoid many duplicates
