### ISSUE TITLE
Add could not be installed [Firefox Dev/macOS]

### ISSUE THREAD

**Issue by tom-new** [younesaassila/ttv-lol-pro#176]
When I try to install the add-on after following the permanent installation instructions I get the following error:

`This add-on could not be installed because it appears to be corrupt.`

When following the temporary instructions, I get this error instead:

```
There was an error during the temporary add-on installation.
Error details

File /Users/tom/Downloads/ttv-lol-pro-2.0.0.zip does not contain a valid manifest
```

I am on macOS Ventura 13.4 and am using Firefox Developer Edition version 115.0b3.

**Comment by juliocoliveira** [comment]
you have to install a release not the source code https://github.com/younesaassila/ttv-lol-pro/releases/download/v2.0.0/v2.0.0-firefox.zip.

To me the release works fine.
I installed on Firefox Dev, and is working (Except from the Kaspersky Bug).
To me the 2.0.0 just works with Konami Code enabled.
