### ISSUE TITLE
Will Firefox standard version always be a temporary install?

### ISSUE THREAD

**Issue by nazsol** [younesaassila/ttv-lol-pro#178]
Should i install the Developer Edition or is there a chance to make it permanent on standard Firefox?

**Comment by younesaassila** [comment]
For now it is but I've sent the version to the Mozilla Add-on store so it'll be published on there. Sent it a week ago and still waiting for their review. They are super slow and I can't do anything about it unfortunately.

**Comment by MichalLechowski** [comment]
Waiting for that, as well. Cannot use 2.x at all because of that :(
