### ISSUE TITLE
Extension blocks the URL's from Twitch their emails

### ISSUE THREAD

**Issue by Rocksterdev** [younesaassila/ttv-lol-pro#182]
Extension blocks the URL's from Twitch their emails

**To Reproduce**
Open a link from Twitch from their emails it will say "This page has been blocked by an extension
Try disabling your extensions."

**Expected behavior**
To just redirect to the page it's supposed to redirect to.

Browser: Chrome Version 114.0.5735.110 (Official Build) (64-bit)

This was already an issue on previous versions but now 2.0 is released it's still a problem. The simple fix would be to check for any context clues in the URL to it being an email link as Twitch uses GET statements to find where their traffic is coming from.

Edit: 

Looking at some of the URLs I got checking for `tt_email_id` & `tt_medium=email` should do the trick in fixing this issue

**Comment by younesaassila** [comment]
Could you post the URL up to the last `/` character? Thanks

**Comment by Rocksterdev** [comment]
https://www.twitch.tv/r/e/eyJsb2NhdGlvbiI6ImN0YSIsImVtYWlsX2lkIjoiNTY4ZmQ0OTItYjJhNi00NjAyLTk3NTUtYmY4Mjc2Y2JjNGNkIiwibmFtZSI6ImNtc3RhbmRhcmRhZmZpbGlhdGVzIiwic291cmNlX2VtYWlsIjoiIiwiY3RhX3ZhbHVlIjoiTE9XIiwiY2hhbm5lbCI6IiIsImxvZ2luIjoiIn0=/63345596/8ee624ae9c3bd572055e3c58e39927e9da0e17f398a0638179d4c3735d092982/p/legal/monetized-streamer-agreement?ignore_query=true&tt_content=cmstandardaffiliates&tt_email_id=568fd492-b2a6-4602-9755-bf8276cbc4cd&tt_medium=email is the whole url this email is link is about the affiliate changes made june 6th i dont know what you specifically needed.

**Comment by younesaassila** [comment]
Thanks! Seems like Twitch uses this /r/ route for all of their tracking needs, including emails.
I'll update it so it only blocks tracking pixels for ads

**Comment by younesaassila** [comment]
Fixed in v2.0.1
