### ISSUE TITLE
A way to see proxy usage

### ISSUE THREAD

**Issue by Lucas559-noob** [younesaassila/ttv-lol-pro#185]
**Is your feature request related to a problem? Please describe.**
Since the new proxy can't get over an amount of simultaneous uses, there should be a way to see how many are using right now.

**Describe the solution you'd like**
Show a bar of current usage of the proxy to know when there will possible outages.

**Describe alternatives you've considered**
A website to see this, maybe there is.

**Comment by zGato** [comment]
This would probably look cool. But the big issue is that proxy usage can't be determined in a reliable way.
If you join a stream and it works, you already have that slot reserved for you. Unless you close that tab you won't get any "connection outage"

Also, a single user can't fill up all the slots. Twitch spaguetti code infrastructure allows that user to open as much streams as he wants, so we've not limited. We may do in the future if we see abuse.
