### ISSUE TITLE
1.9.3 is finally broken.

### ISSUE THREAD

**Issue by TsukiZero** [younesaassila/ttv-lol-pro#188]
Got a forever load issue with and without Twitch Ad Solution Vaft on the side.

**Comment by YheonYeung** [comment]
me too. And 2.0.2 didn't fix my proxy software conflict problem, it's time to say goodbye.

**Comment by thinkpad4** [comment]
@TsukiZero 1.9.3 works fine, Everyone is having the forever loading issue, even people not using TTVLOLPRO,  I was in a few streams today and people kept complaining about error #2000 and forever loading issues.

**Comment by hosekisho** [comment]
@thinkpad4 Nope. The addon is broken. I can load streams fine once I disable it. The people complaining were likely using TTV lol or similar addons.

**Comment by twilight-sparkle-irl** [comment]
Experiencing same issue.

**Comment by ghost** [comment]
**Thankfully, this addon is no longer needed.** uBO does it all, once again, no scripts necessary. (personally tried, tested & able to confirm for 3+ days.)

**Comment by zGato** [comment]
> **Thankfully, this addon is no longer needed.** uBO does it all, once again, no scripts necessary. (personally tried, tested & able to confirm for 3+ days.)

Again, misinforming people. That it **works for you doesn't mean that it works for everyone**. I don't have any adblock except for uBlock Origin on my main browser and I've been ad-free for months. This is likely because of Twitch cookies, as they show for me LT, RU, IE, ES, and other countries :)

Bet you clear cookies and you'll get ads again :)

**Comment by younesaassila** [comment]
Closing this as it only affected api.ttv.lol and they've now fixed the problem on their side it seems like.

**Comment by TsukiZero** [comment]
> @TsukiZero 1.9.3 works fine, Everyone is having the forever loading issue, even people not using TTVLOLPRO, I was in a few streams today and people kept complaining about error #2000 and forever loading issues.

To put it into perspective, I was on Upsidedown_Matt's stream, then after one of the ad prevention refreshes it got the player stuck in the black screen, even after refreshing or clearing cache.

Then tried to isolate:
TTV LOL PRO + Twitch Ad Solutions (Vaft) = Fail
TTV LOL PRO (Whitelisting channel) + Twitch Ad Solutions (Vaft) = Success
TTV LOL PRO alone = Fail
Twitch Ad Solutions (Vaft) alone = Success

So it was definitely something there.
