### ISSUE TITLE
2.0.2 doesn't support FireFox version 89.0

### ISSUE THREAD

**Issue by WhyBee604** [younesaassila/ttv-lol-pro#191]
I was previously using 2.0.0 and starting seeing ads again so I checked the site and saw 2.0.2 exists.  I tried to install that on my FireFox 89.0 and it gives the error "**There was an error during the temporary add-on installation.  Error details: Add-on {76ef94a4-e3d0-4c6f-961a-d38a429a332b} is not compatible with application version. add-on minVersion: 91.1.0.**"  If there is no plan to support versions older than 91.1.0 then I suggest that the front page mention this but of course i'd like it to work for older versions :)

**Comment by zGato** [comment]
Your Firefox version is 2 years behind the current one. Why are you still using it? Makes no sense to me.

**Comment by younesaassila** [comment]
Sorry, there is no plan to support older versions

**Comment by WhyBee604** [comment]
OK thanks for the update.  I like using this old version for a specific addon :)
