### ISSUE TITLE
Incomptaible with FrankerFaceZ emotes in Firefox

### ISSUE THREAD

**Issue by VibeEly** [younesaassila/ttv-lol-pro#193]
**Describe the bug**

FrankerFaceZ emotes don't appear if TTV LOL PRO is enabled.

FrankerFaceZ is an extension for Twitch. They also host a library of Twitch emotes, similar to BTTV and 7TV. To avoid confusion:
FrankerFazeZ - the extension.
FrankerFaceZ emote library - the emotes hosted by FFZ staff. Notably separate from BTTV and 7TV emotes.

https://www.frankerfacez.com/emoticons/

**To Reproduce**
1. Install Firefox on Windows 11.
2. Install FrankerFaceZ.
3. Install TTV LOL PRO from this GitHub using the "Temporary" method.
4. Attempt to use emotes from the FFZ library. BTTV and 7TV emotes work. FFZ library emotes do not work.
5. Turn TTV LOL Pro extension ON and OFF. The FFZ emotes will work when TTV LOL PRO is off. 

**Expected behavior**
FFZ library emotes should work.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 up to date
 - Browser: Firefox up to date
 - Version: 114.1

**Additional context**
I brought up the problem with the FrankerFaceZ team on their discord, and told them I would file a bug report here. 

I've attached 2 screenshots. One shows the emotes not appearing in the emote menu, the other shows them appear (when TTV LOL PRO is disabled).
![Screenshot 2023-06-14 235725](https://github.com/younesaassila/ttv-lol-pro/assets/67596/1ff532b5-609a-453d-8432-17a0c8028188)
![Screenshot 2023-06-15 002830](https://github.com/younesaassila/ttv-lol-pro/assets/67596/379e8d6f-fb06-49ca-9a5b-d70ad51cbf21)

**Comment by zGato** [comment]
Tried to reproduce. My browser directly crashes using FrankerFaceZ alone. With TTV LOL PRO enabled yeah, FFZ are not showing, but without it the browser just crashes lmao. 
Firefox Dev Edition 
@younesaassila script probably. Chrome works just fine.

**Comment by younesaassila** [comment]
Thanks for the report. It was an error with the injected script indeed. Fixed for the next release :)
