### ISSUE TITLE
Improve midroll blocking on Firefox

### ISSUE THREAD

**Issue by younesaassila** [younesaassila/ttv-lol-pro#196]
I've thought about a potential new system for blocking midrolls on Firefox with optimizations turned on:

- Implement a communication system between the page script and the worker script
- On stream load, keep current behavior of proxying first request to prevent prerolls
- Then, the worker sends a message to the page script asking it to generate a new playback token and fetch an updated manifest (all of these requests get through the proxy)
- Video-Weaver links from this manifest are stored for later use
- When an ad is detected, worker script sends message to page script asking for replacements Video-Weaver links
- Page replies with cached Video-Weaver links and restart a new fetching process for next use
- Worker receives these links and replaces the Video-Weaver requests links with one of these ones

This will make the player effectively use fresh links not yet linked to the user's true location.

I don't plan on coding the feature myself, I'm very tired of this project tbh. I'm open to any contribution on this and would highly appreciate them!

**Comment by schipht** [comment]
for firefox users:

I'm using SwitchyOmega extension since v2 release. I didn't get any ad since long time.
You can try this extension until midrolls blocked with ttvlp.

1- install the extension
2- create proxy.txt copy paste below settings into the file then change file extension to bak
3- go to extension settings in browser
4- import proxy.bak file

enjoy ad free stream

settings:

> {"+auto switch":{"profileType":"SwitchProfile","rules":[{"condition":{"pattern":"^https://usher.ttvnw.net/*/*/*/*","conditionType":"UrlRegexCondition"},"profileName":"proxy"},{"condition":{"pattern":"^https://video-weaver.*","conditionType":"UrlRegexCondition"},"profileName":"proxy"},{"condition":{"pattern":"gql.twitch.tv","conditionType":"HostWildcardCondition"},"profileName":"proxy"},{"condition":{"pattern":"passport.twitch.tv","conditionType":"HostWildcardCondition"},"profileName":"proxy"}],"name":"auto switch","color":"#99dd99","defaultProfileName":"direct","revision":"1886964ce63"},"+proxy":{"bypassList":[{"pattern":"127.0.0.1","conditionType":"BypassCondition"},{"pattern":"::1","conditionType":"BypassCondition"},{"pattern":"localhost","conditionType":"BypassCondition"}],"profileType":"FixedProfile","name":"proxy","color":"#99ccee","fallbackProxy":{"port":2023,"scheme":"http","host":"firefox.api.cdn-perfprod.com"},"revision":"188c816f6d3"},"-addConditionsToBottom":false,"-confirmDeletion":true,"-downloadInterval":1440,"-enableQuickSwitch":false,"-monitorWebRequests":true,"-quickSwitchProfiles":[],"-refreshOnProfileChange":true,"-revertProxyChanges":true,"-showConditionTypes":0,"-showExternalProfile":true,"-showInspectMenu":false,"-startupProfileName":"","schemaVersion":2}

**Comment by younesaassila** [comment]
@schipht Hey, please avoid using PerfProd proxies outside of the TTV LOL PRO extension. This config spams the server with requests since SwitchyOmega doesn't implement TTV LOL PRO-specific optimizations. This results in purple screens being more likely for all users of the proxy. Please either use your own proxy in SwitchyOmega or use TTV LOL PRO. Thanks

**Comment by karayelxyz** [comment]
@younesaassila hello i'm sorry heard this. i didn't knew how is your extension working with proxy server.
i didn't get any ads while using firefox proxy with switchyomega.

here is public proxy server settings for switchyomega:

`
{"+auto switch":{"profileType":"SwitchProfile","rules":[{"condition":{"pattern":"^https://usher.ttvnw.net////","conditionType":"UrlRegexCondition"},"profileName":"proxy"},{"condition":{"pattern":"^https://video-weaver.*","conditionType":"UrlRegexCondition"},"profileName":"proxy"},{"condition":{"pattern":"gql.twitch.tv","conditionType":"HostWildcardCondition"},"profileName":"proxy"},{"condition":{"pattern":"passport.twitch.tv","conditionType":"HostWildcardCondition"},"profileName":"proxy"}],"name":"auto switch","color":"#99dd99","defaultProfileName":"direct","revision":"1886964ce63"},"+proxy":{"bypassList":[{"pattern":"127.0.0.1","conditionType":"BypassCondition"},{"pattern":"::1","conditionType":"BypassCondition"},{"pattern":"localhost","conditionType":"BypassCondition"}],"profileType":"FixedProfile","name":"proxy","color":"#99ccee","fallbackProxy":{"port":55555,"scheme":"http","host":"proxy.karayel.xyz"},"revision":"18936320271"},"-addConditionsToBottom":false,"-confirmDeletion":true,"-downloadInterval":1440,"-enableQuickSwitch":false,"-monitorWebRequests":true,"-quickSwitchProfiles":[],"-refreshOnProfileChange":true,"-revertProxyChanges":true,"-showConditionTypes":0,"-showExternalProfile":true,"-showInspectMenu":false,"-startupProfileName":"auto switch","schemaVersion":2}`

> copy this settings into the settings.bak file and install switchyomega extension to your browsers. then import settings.bak file.

**Comment by younesaassila** [comment]
Fixed in 2.3.0
