### ISSUE TITLE
Can't log in while extension is on

### ISSUE THREAD

**Issue by luizzeroxis** [younesaassila/ttv-lol-pro#198]
**Describe the bug**
If the extension is active, you can't log in to Twitch. Seems to be because of some client-side validation that they have before entering your password. I first discovered it when trying to change my password, where it also asks for your password with the same kind of error.

**To Reproduce**
1. Go to https://www.twitch.tv
2. Click on Log In, type in your login information, click Log In
3. Wait a while, an error message saying "Oops! We encountered an unexpected error. Please try again." will appear.

**Expected behavior**
Not to interfere in such matters.

**Screenshots**
![The error](https://github.com/younesaassila/ttv-lol-pro/assets/5658043/42d927ea-bcc8-4bd5-a6c3-3780dddbbdb4)

**Desktop (please complete the following information):**
 - Windows 10, Google Chrome 114.0.5735.134

**Comment by younesaassila** [comment]
Seems like enabling "Laissez-passer" fixes it.
This is due to an integrity token IP mismatch (integrity token is passed to `https://passport.twitch.tv/protected_login` request)

**Comment by inuoshios** [comment]
I'm currently experiencing this error right now, is there a workaround?
<img width="1676" alt="image" src="https://github.com/younesaassila/ttv-lol-pro/assets/59049785/b03cfb03-6ef3-4e1c-8cdc-a69c649bcf11">
