### ISSUE TITLE
v2 Firefox version

### ISSUE THREAD

**Issue by Medivha** [younesaassila/ttv-lol-pro#200]
Would be nice to have an actual firefox version. It is not practical to reinstall the add-on every time you close and open the browser with the temporary attempt.
And for most people, there is no reason to install a dev version of firefox just for this. Where we probably have to set up everything from new (besides some bookmarks import things).
Or I'm missing completely something, but there is no xpi to install from it or on the addon site.

**Comment by younesaassila** [comment]
Please see #190
