### ISSUE TITLE
[Chrome] Midroll adds are getting through when vaft script is disabled.

### ISSUE THREAD

**Issue by Divzed** [younesaassila/ttv-lol-pro#204]
I tried to run TTV LOL PRO v2.1.0 with default proxy (chrome.api.cdn-perfprod.com:4023) and disabled vaft script as recommended.
When I disabled vaft script, midroll ads started getting through. So I re-enabled vaft script and ads disappeared completely.
The disadvantage of Vaft Script + TTV LOL PRO v2.1.0 are long buffering times (sometimes infinite) when entering live channels or even VODs for some reason.

**Comment by zGato** [comment]
What's the user country it shows on the extension popup? Is it your location or RU/AZ/...?

**Comment by Divzed** [comment]
> What's the user country it shows on the extension popup? Is it your location or RU/AZ/...?

I don't know what popup are you talking about and cannot find any info about location in the extension itself, even when copying debug info.

**Comment by zGato** [comment]
![image](https://github.com/younesaassila/ttv-lol-pro/assets/88756568/1ab7eb64-c63e-4fb5-9d00-b40434af337a)

**Comment by Divzed** [comment]
> ![image](https://user-images.githubusercontent.com/88756568/248042624-1ab7eb64-c63e-4fb5-9d00-b40434af337a.png)

That's strange, on my TTV LOL PRO version from Chrome Web Store I don't have this indicator at the top.
![zaf2342](https://github.com/younesaassila/ttv-lol-pro/assets/104203796/9f90e013-ad57-484d-b357-d5eb3be994d5)
But proxy seems to work.
![zaq234](https://github.com/younesaassila/ttv-lol-pro/assets/104203796/7997493f-09d7-4a5e-b393-705cd2e711a9)

**Comment by zGato** [comment]
Then you're not using 2.1.0

**Comment by Divzed** [comment]
> Then you're not using 2.1.0

So what is it then, if not 2.1.0?
![uyt655](https://github.com/younesaassila/ttv-lol-pro/assets/104203796/53c781aa-3c4e-40b1-8d86-fb88cfff0e83)

**Comment by zGato** [comment]
Try disabling other extensions but you have a conflict somewhere.

**Comment by Divzed** [comment]
> Try disabling other extensions but you have a conflict somewhere.

You are right, it was conflict between VAFT script and TTV LOL PRO. Now it shows popup.
![qwer123](https://github.com/younesaassila/ttv-lol-pro/assets/104203796/f09a7f74-c986-4736-9325-a805e59af349)
But the problem is, sooner or later ads will come through when vaft is disabled. I tested it yesterday.

**Comment by zGato** [comment]
Just once you get an ad check on the extension popup status and report back here the info it shows. 
Watching your console log you've been more than an hour watching that streamer without any ad.

**Comment by zGato** [comment]
Quick reminder to not let your player pause/stop. That can cause not getting a free slot and fallbacking to your normal network and get ads.

**Comment by Divzed** [comment]
> Watching your console log you've been more than an hour watching that streamer without any ad.

Log was with enabled vaft entire time.

**Comment by zGato** [comment]
> > Watching your console log you've been more than an hour watching that streamer without any ad.
> 
> This log was with enabled vaft entire time.

Still, you proxied more than 600 weavers. That's a lot of minutes proxied.

**Comment by Divzed** [comment]
> Quick reminder to not let your player pause/stop. That can cause not getting a free slot and fallbacking to your normal network and get ads.

This may be big issue because sometimes I pause/stop player for 3sec to fix twitch random audio bug/distortion that exists for years and I believe it is on the twitch end. The only way to fix it is to pause and resume stream.

**Comment by zGato** [comment]
> > Quick reminder to not let your player pause/stop. That can cause not getting a free slot and fallbacking to your normal network and get ads.
> 
> This may be big issue because sometimes I pause/stop player for 3sec to fix twitch random audio bug/distortion that exists for years and I believe it is on the twitch end. The only way to fix it is to pause and resume stream.

That's not something I can control, so perhaps donate for private proxies access or host your own. Also I don't have that audio issue, it's weird.

**Comment by Divzed** [comment]
I'm still getting ads with disabled vaft script.
![zaq2](https://github.com/younesaassila/ttv-lol-pro/assets/104203796/f51fba84-c620-4142-8020-a6bf348dd76d)
![zaq1](https://github.com/younesaassila/ttv-lol-pro/assets/104203796/816605c5-df72-45e7-ad9f-d3205f981258)
Also getting bombarded like x10 per channel with error #2000 (afternoon EU timezone). When entering channels or even in the middle of watching. Probably because slots are full, overloaded.
![zaq3](https://github.com/younesaassila/ttv-lol-pro/assets/104203796/bcc12409-c40e-4a99-afe9-392690ce0ac8)
I guess TTV LOL PRO + Vaft Script is the only solution for now.

**Comment by zGato** [comment]
The loadbalancer you had connection to is being under maintenance due to an IP change for my provider.
You're not being helpful not saying that it worked for a while for example :)
![image](https://github.com/younesaassila/ttv-lol-pro/assets/88756568/f27849e2-4523-4698-95b8-e88b1a2bace2)

**Comment by zGato** [comment]
I invite you to use VAFT and stop using TTV LOL PRO. Both solutions at the same time won't do shit.

**Comment by Divzed** [comment]
> I invite you to use VAFT and stop using TTV LOL PRO. Both solutions at the same time won't do shit.

It has to do something, error #2000 issue disappears completely + not a single pre-roll, mid-roll ad from what I noticed.
TTV LOL PRO works fine in the middle of the day (EU) for most time and gets really bad afternoon (today/yesterday and days ago). 
Using only vaft without TTV LOL PRO doesn't work at all in my case, ads are getting through almost all the time.

**Comment by zGato** [comment]
> > > Quick reminder to not let your player pause/stop. That can cause not getting a free slot and fallbacking to your normal network and get ads.
> > 
> > 
> > This may be big issue because sometimes I pause/stop player for 3sec to fix twitch random audio bug/distortion that exists for years and I believe it is on the twitch end. The only way to fix it is to pause and resume stream.
> 
> That's not something I can control, so perhaps donate for private proxies access or host your own. Also I don't have that audio issue, it's weird.

That's when the US base users come to play. Almost half of the extension downloads are from US users so...
Check quote, I already gave you a solution. I can't do anything more, I don't have Bezos money to tank 1000 proxies and make a super reliable infrastructure. 

And again, using VAFT with TTV LOL PRO doesn't help. I refuse to try helping you if you don't disable third party Twitch Adblockers. It's a waste of time.
