### ISSUE TITLE
Support for "player.twitch.tv" & third-party websites

### ISSUE THREAD

**Issue by MrChuw** [younesaassila/ttv-lol-pro#206]
**The features that I want.**
The extension doesn't work on the player link.
"https://player.twitch.tv/?channel=(channel_name)&parent=twitch.tv(rest of the URL to make it work)"

**Describe the solution you'd like**
I imagine there isn't much difference from the regular site since the player is the same.

**Comment by MrChuw** [comment]
I saw in the releases that it supposedly has support, but at least here it doesn't show that it's working.

![6a8b1e](https://github.com/younesaassila/ttv-lol-pro/assets/14945734/d14d0a6d-fe72-47d4-886e-be0aa5eeae3f)

**Comment by zGato** [comment]
Did you get any ad? probably not, so it's working.

**Comment by younesaassila** [comment]
Only www.twitch.tv and m.twitch.tv pages are supported as of now

**Comment by kurtdh** [comment]
Any plans on supporting third party sites like twitchtheater.tv? It doesn't use an embed player, it seems to use the regular twitch player. Would be amazing if this addon ever worked on that specific website. I would no longer need to subscribe to twitch turbo every month!

**Comment by amiga-500** [comment]
since it is just a domain thing, one coud just edit the ttv code to include the domains u want right now, install this patch extension via debug mode and ur good to go.  Assuming you don't want to wait & hope the official dev does because it is unlikely he will.

**Comment by kurtdh** [comment]
> since it is just a domain thing, one coud just edit the ttv code to include the domains u want right now, install this patch extension via debug mode and ur good to go. Assuming you don't want to wait & hope the official dev does because it is unlikely he will.

I don't know how to code or do anything like that. I'm just a simpleton. If it's that easy, why wouldn't the dev do it? He just released a large update a few days ago, so he's obviously still putting in a ton of work on the addon.

**Comment by younesaassila** [comment]
It's more than just a domain change. TTV LOL PRO injects a script into the Twitch webpage to make "Proxy ad requests only" work. Changes would be required to make it compatible with other websites. Also, from what I remember, the embed player works differently and gives out "Commercial break in progress" ads much more easily.

**Comment by kurtdh** [comment]
> It's more than just a domain change. TTV LOL PRO injects a script into the Twitch webpage to make "Proxy ad requests only" work. Changes would be required to make it compatible with other websites. Also, from what I remember, the embed player works differently and gives out "Commercial break in progress" ads much more easily.

twitchtheater.tv doesn't use the embed player, it uses the default Twitch player, if that makes things easier?

**Comment by zGato** [comment]
> twitchtheater.tv doesn't use the embed player, it uses the default Twitch player, if that makes things easier?

That website uses the embed player, or some sort of variation, which still causes purple ads, not even using a proxy, at all.
![image](https://github.com/younesaassila/ttv-lol-pro/assets/88756568/363b2886-9787-45ac-aa8a-0e376865ac07)

**Comment by LetsPlayNintendoITA2023** [comment]
no problem i'll just report you all to twitch. go ban someone else.
can't even have a working extension. Lmao what a failure

**Comment by LetsPlayNintendoITA2023** [comment]
wtf do you mean can't fix?
