### ISSUE TITLE
Getting pre roll ads still, not sure if proxy is being used.

### ISSUE THREAD

**Issue by chrcoluk** [younesaassila/ttv-lol-pro#209]
Latest stable Firefox as of 25 June 2023
Load up a stream, about 33% chance of preroll, same as without ttv-lol-pro.

Pre roll's are nasty here, tried all ad blockers etc. was hopeful this would work, but if this is unexpected, I can provide diagnostics info if requested.

Live stream connection appears to be to 'video-edge-78a2db.pdx01.abs.hls.ttvnw.net' which seems the proxy is not working?

Also seems to be no indication its actively loading on twitch, no popup etc.

**Comment by zGato** [comment]
Enable laiser in the options tab and report back.

**Comment by chrcoluk** [comment]
Sorry I only see a few options.

Reset player when midroll detected. (off)
Shaow a banner in popup when update available. (off)
Whitelisted channels (none)
Proxies (api.ttv.lol)
Disable vod proxying (on)
Ignore subs channels (none)

I feel I am looking in the wrong place or perhaps missing something?

--

Ok I pinned the extension icon onto firefox toolbar, and when I click it with a stream open, it does say its being proxied.  I will check it again if I get an ad, this stream I am on now didnt preroll.  Thanks

**Comment by zGato** [comment]
You're using TTV LOL PRO V1 branch which works for some and doesn't for others.
Before switching to the V2 branch, you can try switching proxies to the ones mentioned at https://github.com/younesaassila/ttv-lol-pro/discussions/37

**Comment by Berzerker** [comment]
I'm using v2, and enabled the laissez-passer and am still getting pre-roll ads.

**Comment by zGato** [comment]
Pre-roll ads are not possible with laiser enabled.
Check extension popup and see if it's proxied to RU or some other country which is not where you currently live.

**Comment by chrcoluk** [comment]
It happened again and now I know the reason as I now know where to check, the reason was all proxy servers failed to ping, refreshing the page it worked again via proxy.
