### ISSUE TITLE
Whitelist not showing on chrome

### ISSUE THREAD

**Issue by nedet** [younesaassila/ttv-lol-pro#210]
**Describe the bug**
The whitelist button just is not there

**Expected behavior**

**Screenshots**
<img width="143" alt="image" src="https://github.com/younesaassila/ttv-lol-pro/assets/49131786/9fd27fde-8f05-4c6e-b44a-1ea2dd3584c9">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Version 114.0.5735.134

**Comment by Lucas559-noob** [comment]
V2 is build different, it uses some sort of thing that Firefox have, so you can whitelist, but chrome don't have that.
Is explained somewhere

**Comment by nedet** [comment]
> 

ah so you cant whitelist with chrome now?

**Comment by zGato** [comment]
Whitelisting is currently not available for Chrome but it is for Firefox. This is due to limitations on Chrome Extension Development. https://github.com/younesaassila/ttv-lol-pro#------ttv-lol-pro--
