### ISSUE TITLE
Unable to login to Twitch when extension is active

### ISSUE THREAD

**Issue by FIGBird** [younesaassila/ttv-lol-pro#213]
**Describe the bug**
The extension prevents logging in to Twitch. 

**To Reproduce**
1. Go to Twitch while being logged out of any account
2. Click on 'log in'
3. Enter valid login credentials and attempt to login
4. Twitch fails to log in with unexpected error

**Expected behavior**
When the extension is active the login requests should not be prevented from working

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.1 Cinnamon
 - Browser Crome and Firefox (tried both)
 - Version 2.1.0

**Additional context**
I was able to complete login by disabling the extension, then logging in. This was successfully attempted twice. 
Also note that the account has 2FA, which may be part of the issue.

**Comment by juliocoliveira** [comment]
Indeed, happens the same with me. I can't login, If I disable the extension I'm able to.

**Comment by MisterSheeple** [comment]
Can confirm I get the same problem.

**Comment by zGato** [comment]
This is expected, and has been explained [here](https://github.com/younesaassila/ttv-lol-pro/issues/198#issuecomment-1595381925)
