### ISSUE TITLE
bug: Number of proxied requests stops increasing

### ISSUE THREAD

**Issue by KammererTob** [younesaassila/ttv-lol-pro#216]
**Describe the bug**
The number of proxied requests in the options overlay seem to stop increasing after a certain time/action

**To Reproduce**
Not entirely sure how to reproduce, but it might be related to either switching tabs, moving chrome in the background or moving chrome/tab on to a second monitor

**Expected behavior**
The number should increment for every proxied request

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 114.0.5735.199 (64bit)
 - Using a custom proxy

**Comment by zGato** [comment]
This seems to be reproducible if you get a ghost ad or you make your player get a new streamer.m3u8 request (stream in the background for too long and you tab back in)

Do you have uBlock Origin installed?

**Comment by KammererTob** [comment]
Yes i have uBlock Origin installed and active on Twitch

**Comment by younesaassila** [comment]
Has anyone been able to consistently reproduce this issue? It's possible the bug is caused by the function that clears proxy settings when all Twitch tabs are _supposedly_ closed.

**Comment by younesaassila** [comment]
I've opened a small PR (#222) that potentially fixes this. Can anyone confirm if that is the case?

(Just a small PR, still on my indefinite break from actively working on the project)

**Comment by KammererTob** [comment]
I will build from source and try if i can still reproduce this. It was a bit random before so i might not get back with 100% confirmation tho.

**Comment by KammererTob** [comment]
doh. I am an idiot. I've built v2 branch instead of your PR branch. Will do it again with the correct branch and test

**Comment by younesaassila** [comment]
Fix should be working :)
