### ISSUE TITLE
Pre-rolls getting through on some streams

### ISSUE THREAD

**Issue by djg007** [younesaassila/ttv-lol-pro#217]
Some pre-rolls are getting through. 

Doesn't happen on all streams but some where pre-rolls are getting through.

<img width="1339" alt="Screen Shot 2023-07-10 at 2 53 43 PM" src="https://github.com/younesaassila/ttv-lol-pro/assets/74840825/2b418107-cea4-440c-8d68-b6b9376a9407">

macOS Monterey 12.6
Firefox 114.0.2
Version 2.1.2

**Comment by zGato** [comment]
Are only those purple ads the pre-rolls?

**Comment by djg007** [comment]
> Are only those purple ads the pre-rolls?

Yes. It could be a certain ad because it only happens so often when I pull up a stream. Sometimes I get that and other times I don't. So far after I've waited through an ad or refresh enough, I haven't gotten mid-roll ads after.

**Comment by zGato** [comment]
That's due to the high users using the public proxies at the moment you got an ad / got into a stream. That purple ad is placed instead of a real ad as you're proxying thru an ad-free country.
I'm going to improve these issues for Firefox in the coming weeks, just need to finish some things up

**Comment by djg007** [comment]
Oh ok. Thanks for the heads up. Was wondering why I was getting ads only recently and on only certain streams. Thanks for the help and your work.
