### ISSUE TITLE
[Chrome] Why does this extension need to "read and change all your data on all websites"?

### ISSUE THREAD

**Issue by xi-lef** [younesaassila/ttv-lol-pro#219]
I could not find anything regarding this, so I thought I would just open an issue.

When installing the extension from the Chrome web store, it requires to "read and change all your data on all websites". Why is this the case?
For contrast, the TTV LOL only requires permissions for Twitch-specific URLs, which makes a lot more sense. For Firefox, the required permissions are also very sensible.

Could this be changed, or are these permissions really necessary for some reason? If they are, shouldn't there at least be some sort of disclaimer for why this is necessary?

Kind regards and thank you for your time.

**Comment by younesaassila** [comment]
See #189
