### ISSUE TITLE
Add whitelist channel support to Chrome

### ISSUE THREAD

**Issue by bradstv** [younesaassila/ttv-lol-pro#226]
**Is your feature request related to a problem? Please describe.**
Not really a problem but having to disable the extension on channels I'm subscribed to is not the best.

**Describe the solution you'd like**
Adding a whitelist channel option to Chrome just like Firefox has and V1 had.

**Describe alternatives you've considered**
To prevent stream buffering and long load times, I disable the whole extension when watching someone I'm subbed to. So, when I change to another stream that I'm not subbed to, I get hit when and Ad and have to re-enable the extension.

**Comment by younesaassila** [comment]
This feature has been added to v2.2.0 (in development). Closing this issue
