### ISSUE TITLE
Microsoft Edge Add-on support?

### ISSUE THREAD

**Issue by RoonMoonlight** [younesaassila/ttv-lol-pro#23]
Hey, thank you for your hard work to continue what TTV LOL was!

I mainly use Microsoft Edge as main browser, but do you plan to add support for Microsoft Edge Add-ons? I heard MS Edge Add-ons are less restrictive than Google but not sure if Microsoft does the same to Twitch Adblocker.

**Comment by younesaassila** [comment]
Hey, while the extension is compatible with Microsoft Edge (Chromium), the Microsoft Edge Add-ons store requires new extensions to use Manifest v3.

TTV LOL PRO is currently heavily dependent on Manifest v2 (more precisely the `webRequest` API), so a complete rewrite would need to be done to support Chromium stores, and in the near future Chromium browsers.
The main issue is that while Chromium browser vendors are pushing for Manifest v3, some are not compatible with it yet (like Firefox). Developing and maintaining two separate versions of the same extension would be a nightmare considering the differences between the two manifest versions.

In the meantime, you can install the extension locally (as unpacked) by following the installation guide for Chrome in the README.
