### ISSUE TITLE
Pre-rolls are back

### ISSUE THREAD

**Issue by Myloune** [younesaassila/ttv-lol-pro#233]
Pre-rolls are back on twitch with the new version 2.1.4.

I have a Chrome : 115.0.5790.171 

![chrome_rtacnKxrzO](https://github.com/younesaassila/ttv-lol-pro/assets/35792834/b080499b-71af-4126-aab1-4e14553a56db)

**Comment by younesaassila** [comment]
Please try to enable the "Laissez-passer" option in the extension's options and let us know if that fixes it

**Comment by zGato** [comment]
If you're using public Chrome proxies (aka stock installation) there was a config misconfiguration, and it's already fixed, you shouldn't get that purple ad back again.
