### ISSUE TITLE
Latest version not available in Firefox store

### ISSUE THREAD

**Issue by kurtdh** [younesaassila/ttv-lol-pro#234]
The latest version in the Firefox store is 2.1.3, but the most recent release is 2.1.5. Why is this? Does it take a while to get approved? I am reluctant to upgrade manually, because I'm not sure if that will make it so auto upgrade option will be turned off from the firefox store version. I want to upgrade because I'm getting an error on all Twitch streams when the addon is enabled:

![image](https://github.com/younesaassila/ttv-lol-pro/assets/26121469/3c1c1283-469f-4dfd-867e-e33799e337c7)

**Comment by rwbonesy** [comment]
Yes, they need to be approved by Mozilla.

**Comment by younesaassila** [comment]
It takes a while for Mozilla to approve updates (usually around 5 days).

The issue you're currently experiencing is due to a proxy problem. @zGato is aware of it and trying to resolve it
