### ISSUE TITLE
Updated and im seeing adds mid stream now, wasn't before.

### ISSUE THREAD

**Issue by Trae132** [younesaassila/ttv-lol-pro#236]
I tried enabling the Laisser option which was recommended recently to someone else with pre roll adds however these are mid stream.  I installed and have all default settings other then the Laisser-something option.  I have ublock origin as well, chrome browser.

**Comment by girshcatt** [comment]
I have the same issue

**Comment by rdutta** [comment]
I am getting "Commercial break in progress" screens.

```
TTV LOL PRO v2.1.5
- Install type: normal
- Browser: Firefox 117.0
- OS: Windows NT 10.0
- Passport enabled: true
- Is laissez-passer: false
- Optimized proxies enabled: true
- Optimized proxies: ["firefox.api.cdn-perfprod.com:2023"]
- Normal proxies: ["chrome.api.cdn-perfprod.com:4023"]
- Last ad log entry: {"adType":"midroll","channel":"hasanabi","isPurpleScreen":true,"proxy":null,"proxyTwitchWebpage":true,"proxyUsherRequests":true,"timestamp":1691535498963,"videoWeaverHost":"video-weaver.sin01.hls.ttvnw.net"}
```

```
TTV LOL PRO v2.1.5
- Install type: normal
- Browser: Firefox 117.0
- OS: Windows NT 10.0
- Passport enabled: true
- Is laissez-passer: true
- Optimized proxies enabled: true
- Optimized proxies: ["firefox.api.cdn-perfprod.com:2023"]
- Normal proxies: ["chrome.api.cdn-perfprod.com:4023"]
- Last ad log entry: {"adType":"midroll","channel":"hasanabi","isPurpleScreen":true,"proxy":"firefox.api.cdn-perfprod.com:2023","proxyTwitchWebpage":true,"proxyUsherRequests":true,"timestamp":1691535545205,"videoWeaverHost":"video-weaver.sin01.hls.ttvnw.net"}
```

**Comment by klydeinside** [comment]
Twitch must be doing something. I've been using a VPN to Ukraine to avoid ads for idk like a month or more and now I've been getting them the last couple days. Came here to see if the extension was having the same issues. Seems like it.

**Comment by zGato** [comment]
Well, appreciate you opening an issues page instead of just review bombarding 1 star on the stores.

First of all, the last updates HAVE NOT CHANGED ANYTHING related to AdBlocking and are just minor changes that DO NOT affect anything related to it. 
You opened your issue at 3AM (GMT+2) which is one of the most peak hours on the public proxies. Assuming you're using them, the issue is most likely that. Consider supporting the project or hosting your own proxy.

"I have the same issue" is not helpful. 

Commercial break ads should be gone on Firefox now. I've added more proxies for them. To keep updated, join the official Discord server.

A VPN is one of the worst ways of avoiding Twitch ads, as they're well known for having shitty GeoIP. Twitch uses very outdated GeoIP databases and your Ukraine VPN may be recognised by another country.

**Comment by 0xJsoul** [comment]
I'm not having ads though

**Comment by klydeinside** [comment]
> A VPN is one of the worst ways of avoiding Twitch ads, as they're well known for having shitty GeoIP. Twitch uses very outdated GeoIP databases and your Ukraine VPN may be recognised by another country.

2 days out of a couple months is fine with me. And it seems like it was a fluke anyway. Been running great except that day or two. Maybe it was the server idk. Be interesting to see if the 3 people in this thread are still having issues as well or if it was just those couple of days.

**Comment by zGato** [comment]
> > A VPN is one of the worst ways of avoiding Twitch ads, as they're well known for having shitty GeoIP. Twitch uses very outdated GeoIP databases and your Ukraine VPN may be recognised by another country.
> 
> 2 days out of a couple months is fine with me. And it seems like it was a fluke anyway. Been running great except that day or two. Maybe it was the server idk. Be interesting to see if the 3 people in this thread are still having issues as well or if it was just those couple of days.

Are you confident your VPN provider hasn't changed servers or IPs? Were the ads you've seen in another language or not local to your real location?

**Comment by Trae132** [comment]
> Well, appreciate you opening an issues page instead of just review bombarding 1 star on the stores.
> 
> First of all, the last updates HAVE NOT CHANGED ANYTHING related to AdBlocking and are just minor changes that DO NOT affect anything related to it. You opened your issue at 3AM (GMT+2) which is one of the most peak hours on the public proxies. Assuming you're using them, the issue is most likely that. Consider supporting the project or hosting your own proxy.
> 
Im guessing it was precisely what you mention.  Im using full default Ive not done anything with proxies, wouldnt even know how to if I wanted to use different ones, and it seems to have only been doing it that day.  Ill report back if it returns, thanks for the replies though fellas!
