### ISSUE TITLE
I uploaded it to google chrome via github.

### ISSUE THREAD

**Issue by genedeenek** [younesaassila/ttv-lol-pro#242]
![ttvlol](https://github.com/younesaassila/ttv-lol-pro/assets/142002435/d6be8a93-8570-4b59-a862-3460d545b2b6)
TypeError: Failed to fetch

**Comment by zGato** [comment]
?

**Comment by genedeenek** [comment]
> ?

plumbing systems are working. It shows this as an error. ( Google Translate)

**Comment by genedeenek** [comment]
> ?

The extension works correctly in chrome. It shows this as an Error in the plugin settings. ( Google Translate)

**Comment by younesaassila** [comment]
Cannot reproduce
