### ISSUE TITLE
Firefox asks for proxy credentials in incognito, new Firefox profile, or when Twitch cache is cleared

### ISSUE THREAD

**Issue by younesaassila** [younesaassila/ttv-lol-pro#244]
Firefox 117.0
Check Discord #bug-reports for details
(Proxy credentials are provided in TTV LOL PRO proxy list of course)

**Comment by mattskiiau** [comment]
EDIT:
Seems like that did not resolve the issue. 

-------------

Hi, 
I reported this on discord to you. Thank you for opening an issue. 

I am unsure if this option fixes the issue i've been facing and will text in the upcoming days. 

Within firefox proxy settings, I had "no proxy" selected. 
I updated this to "Auto detect" and ticked "Do not prompt for auth if password is saved".
![image](https://github.com/younesaassila/ttv-lol-pro/assets/20663861/25240c89-21ba-4bdc-b967-741f8381241b)

**Comment by younesaassila** [comment]
Are you still experiencing this issue?

**Comment by mattskiiau** [comment]
> Are you still experiencing this issue?

Not for the longest time. It must have been a local issue.

**Comment by younesaassila** [comment]
Alright thanks, I'll close the issue then
