### ISSUE TITLE
Opening Twitch clip in new tab does not load in Firefox

### ISSUE THREAD

**Issue by tugboat-maguire** [younesaassila/ttv-lol-pro#245]
**Describe the bug**
When opening twitch clip in new tab, the clip that is opened first does not load.

**To Reproduce**

1. enable ttv-lol-pro addon in firefox
2. open a twitch clip in a new tab
3. twitch clip page will never load.

**Expected behavior**
Twitch clip will play

**Screenshots**
[Screencast from 2023-09-01 13-37-41.webm](https://github.com/younesaassila/ttv-lol-pro/assets/36178056/80dffdc3-789a-4ec6-8ed4-40812876a3e1)

**Desktop (please complete the following information):**

- OS: Fedora 38 and Windows 10
- Browser Firefox
- Version [e.g. 22] 116.0.3 and 117

**Smartphone (please complete the following information):**
N/A

**Additional context**
happens on both windows 10 and linux. only first opened clip will fail to load. opening clip again will make it load successfully.

**Comment by zGato** [comment]
Can't repro using FF Dev (118.0b3) so perhaps a FF bug? Younes may be able to discuss further, as it is most likely due to the script injection used for FF optimizations. 
https://i.imgur.com/93SGCrA.mp4

**Comment by tugboat-maguire** [comment]
i found i could only reproduce the issue when this addon is installed: https://addons.mozilla.org/en-US/firefox/addon/redirect-shorts-to-youtube/

not sure how it is conflicting with ttv-lol-pro but ill close issue.
