### ISSUE TITLE
Use my TTV LOL PRO passport causes streams to fail loading.

### ISSUE THREAD

**Issue by EnderShadow** [younesaassila/ttv-lol-pro#246]
**Describe the bug**
The TTV LOL PRO passport option is causing streams to fail loading. VODs still seem to work. Disabling the addon or disabling the TTV LOL PRO passport option allows streams to load

**To Reproduce**

Enable TTV LOL PRO passport and load a twitch livestream

**Expected behavior**

The stream loads

**Screenshots**

![image](https://github.com/younesaassila/ttv-lol-pro/assets/3260768/19e44fe3-1d68-4e0f-8be5-a68f937a1a6d)

**Desktop (please complete the following information):**

- OS: Arch Linux
- Browser Firefox
- Version 116.0.3

**Additional context**

This issue only started happening within the last hour or so.

**Comment by Kryptortio** [comment]
Twitch is currently having issues (possibly in only some regions which could explain why turning of a proxy could help) https://downdetector.com/status/twitch/

**Comment by EnderShadow** [comment]
The issue seems to have gone away now as well.
