### ISSUE TITLE
mid rolls starting to appear 

### ISSUE THREAD

**Issue by Teraisu** [younesaassila/ttv-lol-pro#247]
mid rolls starting to appear with firefox.

**Comment by zGato** [comment]
You're not being helpful. Mid-rolls with Firefox's optimizations are kinda expected in specific scenarios, and they can't be remediated without proxying all requests.

Which types of ads are you seeing, purple ads? real ads? ads in your language? have you clicked the ad and checked the domain (for example some ads companies have .com.uk which can be simple to identify where they're serving the ads from)

Also consider checking the [FAQ](https://github.com/younesaassila/ttv-lol-pro/blob/v2/FAQ.md#q-i-dont-get-any-pre-rolls-but-i-always-get-hit-by-mid-rolls)

**Comment by Teraisu** [comment]
Purple screen ad, I just switched to laissez-passer imma see if it pops up again.

**Comment by zGato** [comment]
Already explained on the Discord server. Laissez won't help, neither will fix it. 
The only fix for it on my end is to add more proxies, but it's not a suitable solution currently. We already have a bunch and adding more is costly. 

aka: a lot of users are using the proxy, and twitch knows about it, either deal with it or host your own.

**Comment by Teraisu** [comment]
Okay

**Comment by Teraisu** [comment]
does watching a stream from someone whos streaming from another country cause ads ?

**Comment by zGato** [comment]
Ads are based on your country/city.

**Comment by Teraisu** [comment]
i havent been receiving ads but from only one stream and its in london and im in NA

**Comment by PatientXero** [comment]
> Already explained on the Discord server. Laissez won't help, neither will fix it. The only fix for it on my end is to add more proxies, but it's not a suitable solution currently. We already have a bunch and adding more is costly.
> 
> aka: a lot of users are using the proxy, and twitch knows about it, either deal with it or host your own.

No, expand or die. That's your ultimatum. You'll end up like the original TTV LOL team if you don't take action to correct the problems. If you have funding problems, start a Patreon.

**Comment by zGato** [comment]
> > Already explained on the Discord server. Laissez won't help, neither will fix it. The only fix for it on my end is to add more proxies, but it's not a suitable solution currently. We already have a bunch and adding more is costly.
> > aka: a lot of users are using the proxy, and twitch knows about it, either deal with it or host your own.
> 
> No, expand or die. That's your ultimatum. You'll end up like the original TTV LOL team if you don't take action to correct the problems. If you have funding problems, start a Patreon.

There's already sponsors (me & Younes) & Ko-fi (only me). The extension is provided for free, time and knowledge it took is completely for free. No, i'm not going to expand, and I'm only expanding for donators. Already paying enough for this. I suggest you donating me $40/month for me to continue with Chrome proxies. 

You really think we're providing any service when we're not, your brain is too small to comprehend.
TTVLOL server costs are basically inexistent, Keep in mind I'm still hosting TTVLOL-like proxies for completely free and they work great.

If you need any proof of payment and what the infrastructure costs are, shoot me up an email: `contact@perfprod.com`

**Comment by PatientXero** [comment]
$40 a month is peanuts, especially when you are monopolizing on FiveM assets. I wouldn't be whining at those using your service. Like all services provided, the vendor has the responsibility of keeping it maintained and not end up in a dumpster fire.

**Comment by zGato** [comment]
> $40 a month is peanuts, especially when you are monopolizing on FiveM assets. I wouldn't be whining at those using your service. Like all services provided, the vendor has the responsibility of keeping it maintained and not end up in a dumpster fire.

You already have the donation links. I expect a $40/month dono from you from now on, thank you!
FiveM assets? what are you even saying, and what is the relation between that and this project?
This is not a service, can you understand it? There won't be any more development into this project due to Twitch as a platform. Enjoy while it lasts.

The project you're talking about has been up for over 2 years now, and will be for the foreseen future. Ad revenue from that project can't sustain TTV LOL PRO proxies by itself.
