### ISSUE TITLE
all twitch requests are no longer getting proxied

### ISSUE THREAD

**Issue by dubbyOW** [younesaassila/ttv-lol-pro#254]
I started experiencing midrolls sometimes and I noticed that I no longer see twitch getting proxied no matter what settings I use, this happens with a default chrome proxy, I wonder if its due to bandwidth/rate limitations, this happens on all twitch channels
im using edge 117.0.2045.31
![image](https://github.com/younesaassila/ttv-lol-pro/assets/119939110/ed9b0282-8c92-4517-9739-b109789df60c)

**Comment by zGato** [comment]
https://github.com/younesaassila/ttv-lol-pro/blob/v2/FAQ.md
If you want a more detailed explanation, join TTV LOL PRO discord and check https://github.com/younesaassila/ttv-lol-pro/issues/252#issuecomment-1723030363

**Comment by dubbyOW** [comment]
I identified that no requests getting proxied was caused by the other vpn extension which was preventing ttv lol pro from taking over twitch requests even if the other vpn extension wasnt running, because it was used as a main proxy for my browser, disabling/removing vpn extension solves the issue

**Comment by dubbyOW** [comment]
I identified that no requests getting proxied was caused by the other vpn extension which was preventing ttv lol pro from taking over twitch requests even if the other vpn extension wasnt running, because it was used as a main proxy for my browser, disabling/removing vpn extension solves the issue 
![image](https://github.com/younesaassila/ttv-lol-pro/assets/119939110/5bb1176d-ee07-42cc-82a8-dae77ec099ad)
for Edge users: turn off/remove 2nd vpn extension 
![image](https://github.com/younesaassila/ttv-lol-pro/assets/119939110/fdd37002-18aa-4927-8a57-fd39215c5b5e)
its supposed to look like this: 
![image](https://github.com/younesaassila/ttv-lol-pro/assets/119939110/b17b8954-06c5-45d1-b487-9d8361b1b830)
