### ISSUE TITLE
Error #2000

### ISSUE THREAD

**Issue by igorpdm** [younesaassila/ttv-lol-pro#255]
In every stream I enter, the broadcast is interrupted by error #2000. This only happens in Chrome.

**Comment by zGato** [comment]
https://github.com/younesaassila/ttv-lol-pro/blob/v2/FAQ.md
If you want a more detailed explanation, join TTV LOL PRO discord and check https://github.com/younesaassila/ttv-lol-pro/issues/252#issuecomment-1723030363
