### ISSUE TITLE
Links break

### ISSUE THREAD

**Issue by Tiffys** [younesaassila/ttv-lol-pro#264]
**Describe the bug**
The extension breaks Twitch links.

**To Reproduce**

1. Turn notifications on for a stream. Then when you get the email...
2. Click "Watch now" or the thing that says click this link. It will never load.
3. You can manually go to the stream's page and watch it while that is still trying to load. It will still be trying to load after the stream ends.

**Expected behavior**
It should instantly just load the twitch page.

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- Browser Firefox
- Version 108.0.1

**Additional context**
Issue doesn't happen without the extension. Though the primary purpose of the extension (blocking ads) works great.

**Comment by younesaassila** [comment]
Could you please share what the start of such a link is? Since the extension blocks links Twitch uses to track ads watched/links clicked it's possible I've missed a subdomain or path to allow

**Comment by Tiffys** [comment]
Ah. I didn't know if it had any kind of personal information. Sure.

https://www.twitch.tv/r/e/eyJsb2NhdGlvbiI6ImFjdGlvbiIsImVtYWlsX2lkIjoiM2Q1MmZjNDYtZWYxOC00ZDM2LWIzNDYtMTM4YjcxNjdiYjY4IiwibmFtZSI6InR3aXRjaF9mYXZvcml0ZV91cCIsInNvdXJjZV9lbWFpbCI6InR3aXRjaF9mYXZvcml0ZV91cCIsImN0YV92YWx1ZSI6IiIsImNoYW5uZWwiOiJoZW55YXRoZWdlbml1cyIsImxvZ2luIjoidmVsaXNhdHJhIn0=/642792185/3c0b4a689174974d465e21de10e613c7ace5bad331fecd0e34dc36953ffb5cf5/henyathegenius?ignore_query=true&tt_content=twitch_favorite_up&tt_email_id=3d52fc46-ef18-4d36-b346-138b7167bb68&tt_medium=email

https://www.twitch.tv/r/e/eyJsb2NhdGlvbiI6ImFjdGlvbl9hbHQiLCJlbWFpbF9pZCI6IjNkNTJmYzQ2LWVmMTgtNGQzNi1iMzQ2LTEzOGI3MTY3YmI2OCIsIm5hbWUiOiJ0d2l0Y2hfZmF2b3JpdGVfdXAiLCJzb3VyY2VfZW1haWwiOiJ0d2l0Y2hfZmF2b3JpdGVfdXAiLCJjdGFfdmFsdWUiOiIiLCJjaGFubmVsIjoiaGVueWF0aGVnZW5pdXMiLCJsb2dpbiI6InZlbGlzYXRyYSJ9/642792185/93397e52800e6423be4fe9eb6289729e4c69c21d8cd989eb1b4e3d13b797964a/henyathegenius?ignore_query=true&tt_content=twitch_favorite_up&tt_email_id=3d52fc46-ef18-4d36-b346-138b7167bb68&tt_medium=email

**Comment by younesaassila** [comment]
Are you using the latest version of the extension? v2.0.1 should have fixed twitch.tv/r/e/ links

**Comment by Tiffys** [comment]
I'm using version 2.2.1

**Comment by younesaassila** [comment]
These links work perfectly fine for me on v2.2.1 Firefox. Did you copy the correct link?

**Comment by Tiffys** [comment]
I did and clicking them from here seem to work for me as well. It seems to have to do with clicking them from inside gmail. So you'll need such a notification of your own to test.
