### ISSUE TITLE
Does this extension work on twitchtheater.tv or other twitch viewing websites?

### ISSUE THREAD

**Issue by kurtdh** [younesaassila/ttv-lol-pro#265]
I use twitchtheater.tv every day and when I check the extension, it doesn't show any active proxies. Does this extension work on this website, and if not, could it be made to?

**Comment by zGato** [comment]
Somehow that website, even if it embeds the stream, gets normal ads on Twitch. (instead of the "preparing stream" one)

I'll check with @younesaassila, but we generally don't support third party websites.

**Comment by younesaassila** [comment]
For now only the Twitch website is supported

**Comment by younesaassila** [comment]
Closing this since issue #206 is already about adding support for the embed player
