### ISSUE TITLE
A few seconds after the page loads the plugin stops connecting to the proxy in Firefox Developer

### ISSUE THREAD

**Issue by fernandoccandidoo** [younesaassila/ttv-lol-pro#266]
The plugin does not load and stops working in Firefox developer, on chome and edge it's normal.  I deactivated all browser plugins and left only TTV LOL PRO.

The page loads, the plugin recognizes a proxy for the first few seconds and then loses connection with the proxy.

Windows 10/11
Version 2.2.1

machines on different networks

![Screenshot 2023-11-03 124551](https://github.com/younesaassila/ttv-lol-pro/assets/61832398/9f13c4d2-f66b-465c-9578-17f81498b0cc) 
Firefox

![Screenshot 2023-11-03 124612](https://github.com/younesaassila/ttv-lol-pro/assets/61832398/258b197c-60a1-4f1c-a5c2-ebe952ba45e5)
Edge

**Comment by zGato** [comment]
As expected whilst using Firefox Optimizations "Proxy ad requests" on your options page.
https://github.com/younesaassila/ttv-lol-pro/blob/v2/FAQ.md#q-my-non-proxied-count-keeps-going-up-is-this-normal
