### ISSUE TITLE
2.2.1 Issues on Firefox

### ISSUE THREAD

**Issue by djg007** [younesaassila/ttv-lol-pro#267]
Trying to load a stream and it constantly buffers then eventually you get "There was a network error. Please try again. (Error #2000)"

**Comment by Merigold117** [comment]
Can confirm that I'm having the same issue on the Firefox browser as well and getting the same error.

**Comment by parknich** [comment]
I am also having the same issue on firefox

**Comment by ghost** [comment]
Same issue but to top it I am getting the purple screen with "ads currently in progress" screen

**Comment by Menotdan** [comment]
Yep, getting the same issue. Maybe I live with ads for now?

**Comment by doctortanuki** [comment]
Not sure if it helps, but clicking "Popout Player" in the settings shows the video and still suppresses ads as far as I can tell (been watching for about 20 minutes now and no ads, so the proxy seems to be working for the popout).

**Comment by Menotdan** [comment]
Also, twitch wouldn't let me log in with when I had the extension enabled which is odd.. (tbf it could've been another extension but I wanted to watch streamers lol)

**Comment by rockerBOO** [comment]
> Not sure if it helps, but clicking "Popout Player" in the settings shows the video and still suppresses ads as far as I can tell (been watching for about 20 minutes now and no ads, so the proxy seems to be working for the popout).

Popout player works but it played an Ad for me. Firefox. Thanks!

**Comment by zGato** [comment]
Issues with the Firefox Public Proxy should be partially patched. We're still working on an issue regarding basically "infinite" loading streams.
For more up to date information, join the official TTV LOL PRO discord.
