### ISSUE TITLE
Possible new domain for ads?!

### ISSUE THREAD

**Issue by sn-o-w** [younesaassila/ttv-lol-pro#268]
Hi. I want to report a problem; I am unsure if this is relevant to TTV LOL PRO, but it may soon become a problem.

I use this extension in both Chrome and Firefox: [https://github.com/besuper/TwitchNoSub](https://github.com/besuper/TwitchNoSub)

For some reason, I get ads when I watch VODs. Twitch appears to serve ads through a new domain: **_gcdn.2mdn.net_**.

I compiled my own TwitchNoSub extension and didn't have any ads with the previously released version of the extension, so Twitch serves ads via amazon-ivs-player >= 1.22.0 with the domain mentioned above?! Or perhaps something's wrong with TwitchNoSub?! I don't see anything related to "gcdn.2mdn.net" in the source code of TwitchNoSub.

What is interesting is that I added **gcdn.2mdn.net** via SwitchyOmega and no longer get ads. I just wanted to share my discovery.

**Comment by djg007** [comment]
How'd you go about adding it to SwitchyOmega? I only have done the settings.bak method and I don't think it's working anymore. Also, not too familiar with how the extensions works. Thanks.

**Comment by sn-o-w** [comment]
> How'd you go about adding it to SwitchyOmega? I only have done the settings.bak method and I don't think it's working anymore. Also, not too familiar with how the extensions works. Thanks.

You manually add new condition:

![Screenshot_21](https://github.com/younesaassila/ttv-lol-pro/assets/2406819/df346b39-fe09-4092-84a8-c9460381f27d)

**Comment by djg007** [comment]
> > How'd you go about adding it to SwitchyOmega? I only have done the settings.bak method and I don't think it's working anymore. Also, not too familiar with how the extensions works. Thanks.
> 
> You add manually new condition:
> 
> ![Screenshot_21](https://user-images.githubusercontent.com/2406819/282337191-df346b39-fe09-4092-84a8-c9460381f27d.png)

Thank you so much!

**Comment by zGato** [comment]
TTV LOL PRO V2 doesn't block VODs ads by design as we recommend to use it alongside uBlock Origin which blocks 100% of them (also banner ones)
