### ISSUE TITLE
Your browser is not currently supported. Please use a recommended browser or learn more here.

### ISSUE THREAD

**Issue by cprin21** [younesaassila/ttv-lol-pro#270]
**Details**
Outdated browser warning when using the addon.

**Desktop**
Fedora Linux, Firefox.

**Comment by zGato** [comment]
This can also be reproduced without using any sort of extension, and it's Twitch's fault, nothing we can do.

Try disabling laissez-passer, may help. Nonetheless Twitch saves your account credentials for a very long time.
