### ISSUE TITLE
Purple screens come in every few minutes

### ISSUE THREAD

**Issue by Aurigium** [younesaassila/ttv-lol-pro#271]
There seems to have been another update on Twitch, which makes the Twitch website unusable. 
Advertisements come in every few minutes. 

I am therefore really hoping for an update from TTV LOL Pro :)

**Comment by zGato** [comment]
TTV LOL PRO is still working as expected.

Read the [FAQ](https://github.com/younesaassila/ttv-lol-pro/blob/v2/FAQ.md) and if you still have issues that are not mentioned there, reply here.

**Comment by djg007** [comment]
It doesn't seem to be working for me as expected. Been getting pre-rolls pretty consistently and mid-rolls seem to buffer more often than usual. I'm using the newest version of Firefox on Mac.

**Comment by ddemarco5** [comment]
I'm seeing this behavior too, but I'll provide a bit more clarification here...
I've played around with settings a bit and "Proxy ad requests only" (firefox optimized proxies) isn't working totally as expected.
Like mentioned by the reporter, occasionally ads will come through. The temporary workaround is to simply change the settings options to "Proxy all requests" to mimic the behavior of Chrome.
This isn't entirely desirable, however, as **many** more requests are made through the proxy, about one every second.

I've got a few ads that made it through lingering in the ad log. I'll post it here.
[ttv-lol-pro_ad-log.json](https://github.com/younesaassila/ttv-lol-pro/files/13556494/ttv-lol-pro_ad-log.json)

I'm running my own proxy through Kazakhstan, I've done a lot of testing and it does work correctly, again, narrowed the issue down to optimized proxies.
If you want I can post a snapshot of the squid log, though I'm not sure how useful that would be.

**Comment by younesaassila** [comment]
Can anyone else confirm getting pre-rolls with Firefox's "Proxy ad requests only" option? That shouldn't happen since the first requests to the stream are always proxied. Midrolls can show up with this option, it's a known issue (see #196).

**Comment by younesaassila** [comment]
@ddemarco5 Does using "Proxy ad requests only" with your own proxy show pre-rolls? This could help me figure out whether this is a proxy issue or extension issue

**Comment by ddemarco5** [comment]
Ah, I didn't realize pre-rolls showing in optimized proxies was a known issue. I'll have to try to replicate the issue again, but I'm pretty sure what was happening was I was getting something more akin to an insta-midroll. If memory serves I was looking at a longer than typical buffering screen (30ish seconds) and I'd get an ad. Other than that all I got was midrolls.

I'll try and double check but I'm pretty sure you'll be able to just mark this as a dup of #196

**Comment by younesaassila** [comment]
Thank you. Also just to be clear the known issue is about midrolls, not prerolls :)

**Comment by djg007** [comment]
I still get this screen periodically in pre-rolls:

<img width="2079" alt="Screenshot 2023-12-05 at 5 58 30 PM" src="https://github.com/younesaassila/ttv-lol-pro/assets/74840825/58a411f7-b116-4cbd-b247-f227d26b5fe4">

**Comment by zGato** [comment]
That can't be bypassed with proxies.

![image](https://github.com/younesaassila/ttv-lol-pro/assets/88756568/d4c6a425-e8ef-420a-b2e5-accd31c3f0e5)

**Comment by younesaassila** [comment]
@djg007 Do the purple screens you see have a countdown timer like the one posted by @zGato above?

**Comment by djg007** [comment]
> @djg007 Do the purple screens you see have a countdown timer like the one posted by @zGato above?

They do. They're typically 30 second countdowns, but I've gotten as long as 2 1/2 minutes sometimes but rarely.

**Comment by younesaassila** [comment]
> > @djg007 Do the purple screens you see have a countdown timer like the one posted by @zGato above?
> 
> They do. They're typically 30 second countdowns, but I've gotten as long as 2 1/2 minutes sometimes but rarely.

Hmm unfortunately these cannot be bypassed for now. If these come in too frequently, consider using scripts like VAFT. Twitch prefers destroying the viewing experience even in ad-free countries...

**Comment by C0deTalker** [comment]
On firefox I'm getting prerolls and midrolls with "proxy all requests" enabled.

**Comment by younesaassila** [comment]
> On firefox I'm getting prerolls and midrolls with "proxy all requests" enabled.

Sorry about that, the Firefox proxy is currently down (see https://status.perfprod.com)

**Comment by SakhJack** [comment]
just went back to Purple Adblock, no prerolls or commercial break purple screen 
I recommend if 5-8 sec video delay doesn't bother you
