### ISSUE TITLE
There was a network error. Please try again. (Error #2000)

### ISSUE THREAD

**Issue by cprin21** [younesaassila/ttv-lol-pro#276]
**Describe the bug**
Instead of a stream playing there is a popup saying "There was a network error. Please try again. (Error #2000)".

**Desktop (please complete the following information):**
- Browser Chrome

**Comment by zGato** [comment]
There's an ongoing issue with the Chrome public API. This proxy is not supported and given as courtesy so it will be fixed once I have some free time.

Donate to the project to bypass the queue for the restricted proxies, host your own proxy or switch to Firefox where public proxies are supported & available are some of your alternatives. You can also look for another solutions.
