### ISSUE TITLE
Twitch video player buttons become unclickable a few minutes after opening/loading a stream

### ISSUE THREAD

**Issue by Joshdes** [younesaassila/ttv-lol-pro#280]

**Comment by Joshdes** [comment]
Spoke too soon, seems to either be caused by a uBlock origin filter or an interaction between uBlock and TTV LOL. Couldn't reproduce after disabling uBlock origin.

**Comment by younesaassila** [comment]
Do you use any uBlock script like VAFT?

**Comment by younesaassila** [comment]
This is caused by VAFT

**Comment by Xt-8** [comment]
I also have this issue and I do not use VAFT. It is fairly recent, not sure exactly how long, maybe a few weeks.

**Comment by TheEnhas** [comment]
If using uBO (or any other compatible blocker), add the following cosmetic filter:

`www.twitch.tv##.stream-display-ad__container_lower-third`

I haven't had any issues since adding that, and I also had the same problem and I don't use VAFT either.
