### ISSUE TITLE
2.3 &  Firefox

### ISSUE THREAD

**Issue by Anony400** [younesaassila/ttv-lol-pro#292]
I just manually updated to 2.3 for Firefox. I have to add the add-on every time I close & open Firefox.

1) When will 2.3 be added to firefox add-on page?

2) Can someone explain, in options settings, passport settings (the ordinary, official, and diplomatic bar and the drop down list)?

**Comment by younesaassila** [comment]
1. When Mozilla approves the extension (submitted yesterday, could take 6-8 days)

2. This slider controls what types of request get proxied. Default (ordinary) should be fine for most people. Only increase this slider if you're constantly seeing ads with the current config

Note: As of writing this, the Firefox proxy is down. Changing the slider won't improve anything. We're working to restore the proxy as soon as possible.
