### ISSUE TITLE
Custom Proxy Server "127.0.0.1:8888" Not Working in Version 2.3.0, Worked in 2.2.3

### ISSUE THREAD

**Issue by imBilalx** [younesaassila/ttv-lol-pro#295]
**Description:**
In version 2.3.0, my custom proxy server ("127.0.0.1:8888") doesn't function properly. When using the default settings provided in a fresh installation, there are no problems. The same custom settings successfully worked in version 2.2.3.

**Screenshots:**
2.2.3:
<img width="677" alt="7b603c939800314838774532d85c6f0f5e62d0110c70c4fb036be44e50e5cfe9" src="https://github.com/younesaassila/ttv-lol-pro/assets/97373943/c90f76a9-3111-43b5-b1ea-bf2b0f4f4996">
<img width="1700" alt="369e48ee17e996ac2b1860a75c2f33b8886fc6daf2e1742893b2053f6028a55e" src="https://github.com/younesaassila/ttv-lol-pro/assets/97373943/d68621ed-d72c-4674-9662-4f4cbdb81cdf">
<img width="313" alt="671e3caa5cf22a691083f16bb650357e2758a454a414d4fe34cee3ea61140a1f" src="https://github.com/younesaassila/ttv-lol-pro/assets/97373943/f5886d95-8532-42a5-8ff8-1aa506afe2bc">

2.3.0
<img width="681" alt="96d401c22384e0ee86abb8b09b34d17d2a036ea1c684cdee2cb3fdc0f3e774cf" src="https://github.com/younesaassila/ttv-lol-pro/assets/97373943/7ca8f515-6c44-4869-9208-0197733b336c">
<img width="791" alt="4e4bb17199691e82afb5959e5a2aba35d93ae7eaff8e09aecb5c6e861ef9d694" src="https://github.com/younesaassila/ttv-lol-pro/assets/97373943/aa0be52f-b568-48a4-9396-d5fb9b61d872">
<img width="306" alt="b1d1595867832b9b0b2db3a8dc1037b82360312b9c2dc9da6189c5e521aec734" src="https://github.com/younesaassila/ttv-lol-pro/assets/97373943/8dc33737-320c-4f2f-96cc-d87c6085b95e">

**Steps to Reproduce:**
1. Setting up custom proxy server "127.0.0.1:8888"
2. Sending requests via chosen location (typically IL)

I am using the combination of gluetun and an iVPN server; all my requests using 127.0.0.1:8888 are redirected via the selected server location.

**Environment:**
I observed this behavior on both Chrome and Arc Browser, running on a Macbook M3 Max with macOS Sonoma Version 14.2.1.

**Comment by zGato** [comment]
There is a bug with 2.3.0 if you're using IPv4 proxies. 2.3.2 has been released to fix that. https://github.com/younesaassila/ttv-lol-pro/releases/tag/v2.3.2

You can manually install it or wait for the update on the Chrome Web Store. Alternatively, you could link any subdomain of yours to 127.0.0.1 and use that in the meantime (or edit Windows' hosts file)
