### ISSUE TITLE
Weird Huge Firefox Ram usage (over 90%)

### ISSUE THREAD

**Issue by tommyfeeley** [younesaassila/ttv-lol-pro#302]
**Describe the bug**

**To Reproduce**
Having a stream (multiple will make it more likely but only one process will have the insane usage) on Twitch open, and then doing stuff in the background going to and from different tabs. I have ublock origin on, and then at that point I believe I had normal TTV LOL on (this could've been wrong everything else 100% though), and this one. Turning TTV LOL Pro off stopped it. Usage would be ~25GB of RAM, on my 32GB of ram PC. Windows 10, most updated Mozilla Firefox. Basically the rest of the extensions I have are just twitch chat extension ones. And then closing that 1 high usage process, the rest of my firefox behaves normal just the twitch stream when you go to that tab it will be crashed/frozen. I feel like at this stage almost, if not every time, I am not actually in the stream's tab I have it in the background so I'm guessing thats a big part.

**Expected behavior**

**Screenshots**

![date](https://github.com/younesaassila/ttv-lol-pro/assets/73509256/28a9a0fe-b54c-4f7f-b4b8-1a7df5f6f7f4)
![ahhh](https://github.com/younesaassila/ttv-lol-pro/assets/73509256/89a04fb9-f34c-4ca7-b495-93e506eff9e2)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by younesaassila** [comment]
I'll try to optimize the extension's memory usage for the next version. Let me know if this happens frequently

**Comment by tommyfeeley** [comment]
Ok awesome let me know if you make any major changes and ill report back if it fixed/got worse or whatever. Been using generic TTV Lol last few days but it doesnt block ads at all the midrolls play every time.

**Comment by younesaassila** [comment]
Regular TTV LOL hasn't been working for a while, that's actually part of what prompted me to make this fork

**Comment by salami0133** [comment]
I recommend using Firemin 11 for lower RAM usage

![image](https://github.com/younesaassila/ttv-lol-pro/assets/29978081/d7ea71ba-2572-4251-8dd1-233bd5cc90b5)
