### ISSUE TITLE
Extension asking for username/password for default proxies

### ISSUE THREAD

**Issue by younesaassila** [younesaassila/ttv-lol-pro#305]
**Clicking on "Sign in" without filling in any credentials should make the popup disappear and the extension start proxying**

**Comment by zGato** [comment]
There's an ongoing issue with the authentication server. This is causing the login prompt to appear to users when the load balancers should've already been authenticated. 

Alternatively, some proxy servers are also experiencing packet loss at this moment.

No ETA on a fix currently.
