### ISSUE TITLE
Streams won't load and buffer often

### ISSUE THREAD

**Issue by djg007** [younesaassila/ttv-lol-pro#306]
For the past few days I've been constantly getting Error #2000. The stream would just buffer and eventually say that error. Sometimes refreshing works but mostly I get that error with no luck.

Using the newest version of Firefox on Mac and 2.3.4.

**Comment by Jafner** [comment]
Same here. Firefox 123.0 on Windows 11.  

I was able to load one stream, but it seems like a 5-10% chance to work when I refresh. It doesn't fail 100% of the time.

**Comment by PHY1643** [comment]
Linux (Pop!_OS) with Firefox 123.0 here. I'm seeing the same issue, but it's rather hit-or-miss. Sometimes a stream exhibits this behavior, and sometimes it loads immediately without further issue. And after testing this across several streams (some followed, some not; some subscribed, some not), I can't find any consistent pattern. Makes me wonder if this is a server-side issue.

**Comment by younesaassila** [comment]
Sorry about that. Proxies are struggling because from what I understand some are offline due to the authentication bug from 1-2 days ago. zGato will fix this once he has some free time for the project. Thank you for your understanding
