### ISSUE TITLE
Streams no longer being proxied

### ISSUE THREAD

**Issue by Azingus** [younesaassila/ttv-lol-pro#308]
**Describe the bug**
Since one or two days ago, streams are not getting proxied anymore whatsoever. I already reset the settings to default and cleared my browser cache - to no evail.

**To Reproduce**

1. Go to twitch.tv
2. Open any stream
3. Check the proxy status on the extension
4. "Using optimized proxies" but the stream is not proxied

**Expected behavior**
Proxies should have been used, but they are not. There is also not even a pop-up anymore like a week or so ago that prompted you to enter username and password for the proxy. Previously it would proxy the stream through Russia, but now it still says Germany.

**Screenshots**
<img width="228" alt="image" src="https://github.com/younesaassila/ttv-lol-pro/assets/43013401/ccddb234-6cea-4b1f-897d-7c7ba2c48de0">

**Desktop:**

- OS: Windows 10 23H2
- Browser: Google Chrome
- Version: 122.0.6261.112

**Comment by younesaassila** [comment]
Hey, is that the case for all channels or just specific channels?
Could you also please post your debug info (button in extension popup)? Thanks

**Comment by Azingus** [comment]
Hey,

this happens on all streams. I tested over 10 different streams so far and it's always the same result. Following is the debug info I generated while watching a stream with the issue in effect.

**Debug Info**
Extension: TTV LOL PRO v2.3.4 (normal)
Browser: Chrome 122.0.0.0 (Windows NT 10.0)
Options:
- Passport level: 0
- Anonymous mode: true
- Using optimized proxies: ["chromium.api.cdn-perfprod.com"]
Channel name: grubby
Stream status:
- Proxied: 0, Not proxied: 4
- Proxy: N/A
- Country: DE
Proxy level of control: controlled_by_other_extensions

Not sure what the last line means, but I did not add any extensions recently. These are the extensions I have installed (ABP is disabled on most websites, I only use it for a few that UBO struggles with somehow)

<img width="933" alt="image" src="https://github.com/younesaassila/ttv-lol-pro/assets/43013401/0bb64b76-0ae0-430e-9d8a-89c0c7cf79cd">

**Comment by younesaassila** [comment]
Hmm do you use a VPN perhaps? Last line of debug info means the extension asked Chrome to control your browser's proxy settings but got denied.

**Comment by Azingus** [comment]
I do not use a VPN. I have a Pi-Hole running in my network, could that be an issue? Then again, the Pi-Hole is already active for a few months, so way longer than the time since the issue first surfaced.

**Comment by younesaassila** [comment]
Try to click the "Unset Pac Script" under "Troubleshooting" in TTV LOL PRO's options. If that doesn't work then there must be one extension using a proxy I think?

**Comment by Azingus** [comment]
That seems to have done the trick, thanks!

**Comment by younesaassila** [comment]
Oh wow never thought that button would fix anything haha. Glad to know! :)

**Comment by Lucas559-noob** [comment]
> Hey,
> 
> this happens on all streams. I tested over 10 different streams so far and it's always the same result. Following is the debug info I generated while watching a stream with the issue in effect.
> 
> **Debug Info** Extension: TTV LOL PRO v2.3.4 (normal) Browser: Chrome 122.0.0.0 (Windows NT 10.0) Options:
> 
> * Passport level: 0
> * Anonymous mode: true
> * Using optimized proxies: ["chromium.api.cdn-perfprod.com"]
>   Channel name: grubby
>   Stream status:
> * Proxied: 0, Not proxied: 4
> * Proxy: N/A
> * Country: DE
>   Proxy level of control: controlled_by_other_extensions
> 
> Not sure what the last line means, but I did not add any extensions recently. These are the extensions I have installed (ABP is disabled on most websites, I only use it for a few that UBO struggles with somehow)
> 
> <img alt="image" width="933" src="https://private-user-images.githubusercontent.com/43013401/311466925-0bb64b76-0ae0-430e-9d8a-89c0c7cf79cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MDg5NDQsIm5iZiI6MTcxMDgwODY0NCwicGF0aCI6Ii80MzAxMzQwMS8zMTE0NjY5MjUtMGJiNjRiNzYtMGFlMC00MzBlLTlkOGEtODljMGM3Y2Y3OWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDAwMzcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MTM1OTBkNGNiZDc4YjhhY2MzOWIxYjY0MjYzOTBmOTdiYTZkOTJlMzhmYTYxN2ZiMjg1OWRiMDdlYTYxZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.62qn6kKbSepUYkkpSD1Bk7BGCTS_mCJU0RokLb9i4mQ">

would not those 2 adblockers conflit?

**Comment by Azingus** [comment]
> > Hey,
> > this happens on all streams. I tested over 10 different streams so far and it's always the same result. Following is the debug info I generated while watching a stream with the issue in effect.
> > **Debug Info** Extension: TTV LOL PRO v2.3.4 (normal) Browser: Chrome 122.0.0.0 (Windows NT 10.0) Options:
> > 
> > * Passport level: 0
> > * Anonymous mode: true
> > * Using optimized proxies: ["chromium.api.cdn-perfprod.com"]
> >   Channel name: grubby
> >   Stream status:
> > * Proxied: 0, Not proxied: 4
> > * Proxy: N/A
> > * Country: DE
> >   Proxy level of control: controlled_by_other_extensions
> > 
> > Not sure what the last line means, but I did not add any extensions recently. These are the extensions I have installed (ABP is disabled on most websites, I only use it for a few that UBO struggles with somehow)
> > <img alt="image" width="933" src="https://private-user-images.githubusercontent.com/43013401/311466925-0bb64b76-0ae0-430e-9d8a-89c0c7cf79cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MDg5NDQsIm5iZiI6MTcxMDgwODY0NCwicGF0aCI6Ii80MzAxMzQwMS8zMTE0NjY5MjUtMGJiNjRiNzYtMGFlMC00MzBlLTlkOGEtODljMGM3Y2Y3OWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDAwMzcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MTM1OTBkNGNiZDc4YjhhY2MzOWIxYjY0MjYzOTBmOTdiYTZkOTJlMzhmYTYxN2ZiMjg1OWRiMDdlYTYxZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.62qn6kKbSepUYkkpSD1Bk7BGCTS_mCJU0RokLb9i4mQ">
> 
> would not those 2 adblockers conflit?

I always have ADB+ turned off on twitch so I don't know
