### ISSUE TITLE
Extremely slow loading

### ISSUE THREAD

**Issue by TerraDK** [younesaassila/ttv-lol-pro#311]
**Describe the bug**
When loading a twitch channel, the stream takes an extremely long time to load. Page and chat loads instantly. This does not happen with ttv lol pro disabled.

**To Reproduce**
Visit any live twitch channel

**Screenshots**
![firefox_23CS73rneu](https://github.com/younesaassila/ttv-lol-pro/assets/46207023/a5106736-5fe5-4dfd-8656-920726c43902)

**Desktop (please complete the following information):**
- Firefox
- Version 123.0.1 (64-bit

**Comment by zGato** [comment]
Not a bug, it's expected. Public proxies have rate limits on them due to the amount of users using them.
https://wiki.cdn-perfprod.com/
