### ISSUE TITLE
Getting ads/not being proxied

### ISSUE THREAD

**Issue by Lucas559-noob** [younesaassila/ttv-lol-pro#312]
**Describe the bug**
Ads are being show like if extension was disabled, proxies are set to my country(idk why)

**To Reproduce**

1. Go to an stream
2. Wait for it load
3. Get an ad

**Expected behavior**
Block ads

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 8.1
- Browser edge
- Version 109

**Debug Info**
Extension: TTV LOL PRO v2.3.5 (normal)
Browser: Microsoft Edge 109.0.1518.140 (Windows NT 6.3)
Options:
- Passport level: 0
- Anonymous mode: true
- Using optimized proxies: ["chromium.api.cdn-perfprod.com"]
Channel name: chratosgameplay
Stream status:
- Proxied: 0, Not proxied: 13
- Proxy: N/A
- Country: BR
Proxy level of control: controlled_by_this_extension

Should I increase the passport?
Maybe this the reason 
![image](https://github.com/younesaassila/ttv-lol-pro/assets/54007604/3a3ec5cf-ab08-4240-9f6c-138ccb30d85c)

**Comment by Maverynthia** [comment]
I increased the passport and the ads are still not being proxied.

**Comment by younesaassila** [comment]
Chromium proxy is down at the moment. Increasing the passport is only useful if seeing ads (real ones, not Commercial break in progress screens) AND streams being proxied as usual.

**Comment by beerninja** [comment]
> Chromium proxy is down at the moment. Increasing the passport is only useful if seeing ads (real ones, not Commercial break in progress screens) AND streams being proxied as usual.

I think Firefox just went down too.  Was working this morning and now it's not loading any stream unless I disable the extension.

**Comment by younesaassila** [comment]
> > Chromium proxy is down at the moment. Increasing the passport is only useful if seeing ads (real ones, not Commercial break in progress screens) AND streams being proxied as usual.
> 
> 
> 
> I think Firefox just went down too.  Was working this morning and now it's not loading any stream unless I disable the extension.

That's probably the rate limiting. If we don't rate limit Twitch shows "Commercial break in progress" screens to all users of the proxy
