### ISSUE TITLE
TTV LOL PRO not blocking preroll ads upon navigating to a new stream

### ISSUE THREAD

**Issue by FabledGumbo** [younesaassila/ttv-lol-pro#314]
**Describe the bug**
TTV LOL PRO successfully blocks midroll ads, but I still receive an ad in progress screen when I first start viewing a new stream.

**To Reproduce**

1. Navigate to a Twitch stream you haven't viewed recently.

**Expected behavior**
Ad should be blocked, stream should play without commercial break notification

**Screenshots**
[https://cdn.discordapp.com/attachments/153043548088958976/1225995425782431815/image.png?ex=66232837&is=6610b337&hm=3a08b40cadaf8771be906ca37d47fa742ad54e46028e805545a4da5007e2bdc4&](url)

**Desktop (please complete the following information):**

- OS: Windows 10 Pro 22H2, OS build 19045.4046
- Browser Firefox
- Version 124.0.1 (64-bit)

**Additional context**
Is this a proxy limitation or an extension limitation? Could I resolve this by configuring the extension to route through a proxy hosted in a different country?

**Comment by zGato** [comment]
Not an extension-wise "issue", please check [wiki](https://wiki.cdn-perfprod.com/guides/extension/troubleshooting#i-get-commercial-break-in-progress-a-ds)

> Is this a proxy limitation or an extension limitation? Could I resolve this by configuring the extension to route through a proxy hosted in a different country?

Proxy limitation, country doesn't matter, but number of users in the same proxy triggers that on twitch's servers.
