### ISSUE TITLE
Latest version 2.3.6 for firefox prevents any twitch stream from loading

### ISSUE THREAD

**Issue by RetiredDinosaur** [younesaassila/ttv-lol-pro#316]
**Describe the bug**
I think Twitch are up to some shenanigans and have changed something on their backend today which prevents any stream from loading using the latest version of the addon for Firefox. Disabling the addon in cures the issue.

- OS: Windows 10
- Browser: Firefox
- Version: 124.0.2 (64-bit)

**Additional context**
Did not have this issue over the weekend

**Screenshot**
![error](https://github.com/younesaassila/ttv-lol-pro/assets/35304665/884f0b8b-3198-4102-a473-abba734cbb6e)

**Comment by LoVega1337** [comment]
Not only v2, but also v1 that was working pretty solid until today. So either the Proxies broke or like you said something on Twitch's end changed. I can't even open the Options from v1 anymore since the Extension's options just doesn't show up anymore when clicking on them.

**Comment by zGato** [comment]
V1 is deprecated and no longer supported.
Streams load just fine on my end, so to OP, please disable third party Twitch AdBlockers and/or other extensions and keep TTV LOL PRO and stock uBlock Origin only and report back if there's still issues.
![imagen](https://github.com/younesaassila/ttv-lol-pro/assets/88756568/b94a6e1c-4dff-43b1-ac92-ffdb89a0c588)

**Comment by RetiredDinosaur** [comment]
Disabled all other addons including ublock, issue persists.

Did some digging up and even although the addon is set to auto update and I assume it was updated, I was running 1.9.3.

![version](https://github.com/younesaassila/ttv-lol-pro/assets/35304665/63483bb9-c627-427b-8af0-f4227fac0d9f)

Removed the addon from Firefox and re-downloaded it from https://addons.mozilla.org/en-GB/firefox/addon/ttv-lol-pro/ and we seem to be back in business.

**Comment by zGato** [comment]
Just to clarify @RetiredDinosaur, auto-update works from V2, as we didn't want to push updates to V1 users, as you can see in your specific scenario, you've been able to use V1 for almost a year since V2 release until it broke, so no point on autoupdating if it still works for some.

**Comment by JunkiEDM** [comment]
Wish v1 was still supported since v2 has never worked at blocking ads for me since it was introduced

**Comment by zGato** [comment]
V1 is not reliable and Twitch already broke it once.
https://wiki.cdn-perfprod.com/v/v1/current-state

This means, Twitch is not blindly paying kasada for their services just for fun, but they had some intentions on blocking third party Twitch stuff. They reverted the change, but most likely will come back at a later date.

If you wish to troubleshoot TTV LOL PRO V2 not working for you then feel free to join the Discord server. V2 has worked for basically everyone, even to the hardest cases of Twitch Affiliates/Partners that get tracked-based ads on the information they provided to Twitch.

V1 barely works for most people in PC, for Mobile it's even partially broken in some regions. V2 is not.

V1 proxies hosted by me are still out there, and I don't have plans on removing them, and V1 can't really be much more improved than what it currently is, as it's a limited solution.

**Comment by RetiredDinosaur** [comment]
@JunkiEDM 1.9.3 didn't let through a single ad for me until it stopped working 2 days ago. I've already noticed the odd ad slip through on 2.3.6 and now this

![commercial](https://github.com/younesaassila/ttv-lol-pro/assets/35304665/8146ef5d-264f-44c4-bcb6-dd2f4ba81a4c)

**Comment by zGato** [comment]
@RetiredDinosaur TTV LOL PRO V1 is deprected and unsupported, which means, it may or may not work for you. Only recommended to use by advanced users.

TTV LOL PRO V2 as a extension works just fine, and prevents Twitch ads just fine, but maybe you forgot to read wiki. That's a known "issue"
