### ISSUE TITLE
Troubleshooting "Clear Session Storage" Button?

### ISSUE THREAD

**Issue by MonfGeiger** [younesaassila/ttv-lol-pro#321]
The last time i cleared my browser's "Session", i had to re-log into everything all over again. i JUST did so, and i'm not too keen on doing it again. So....does this button really clear my browser's session storage entirely, or only specifically relating to twitch?

**Comment by ghost** [comment]
> The last time i cleared my browser's "Session", i had to re-log into everything all over again. i JUST did so, and i'm not too keen on doing it again. So....does this button really clear my browser's session storage entirely, or only specifically relating to twitch?

This should not affect other sites, or even twitch in general. Are you clearing it from the ttvlolpro extension itself? via clicking the extension>options>Scroll down to troubleshooting and clicking "clear session storage"

**Comment by MonfGeiger** [comment]
i havent even remotely _touched_ that specific button yet

when it comes to clearing the "Session" of my browser, or cleaning my browser in general, i usually clean my browser with the default method in "Clear Recent History", checkmarking everything BUT site settings (just in-case), and to clean it further, i use the following CCleaner (with winapp2.ini file included for more options) options here to be as through as i can be
![Capture](https://github.com/younesaassila/ttv-lol-pro/assets/28603306/5bde4659-a7cb-4e53-aa59-d390d1885646)

I just wanted to be doubly sure that if i HAVE to click on that button in the addon anytime in the future, that it won't screw up my current browsing session any, especially since when i tried to look it up in the wiki, the troubleshooting entry was completely blank, with absolutely nothing

**Comment by younesaassila** [comment]
The button clears the extension's session storage, not your browser's.
