### ISSUE TITLE
Feature request: more filter options

### ISSUE THREAD

**Issue by kurtdh** [younesaassila/ttv-lol-pro#325]
I would like to use this addon just on a couple of different twitch usernames, but have it be disabled for all the rest. There doesn't seem to be an easy way to do this in the addon and was wondering if you could create an inverse whitelist, where the addon remains inactive but only for the specific streams you select.

**Comment by zGato** [comment]
What's the true practical benefit on this? Or more specific, what's your situation that would benefit you for having this? Perhaps you're subbed to a lot of channels?

**Comment by kurtdh** [comment]
> What's the true practical benefit on this? Or more specific, what's your situation that would benefit you for having this? Perhaps you're subbed to a lot of channels?

I got banned from a channel just for being on the enemy team in game. So now if I want to watch that stream, I have to watch it logged out in a private browser window. I would like to use TTV LOL PRO in that case, so I don't get ads. I don't want it enabled for all the streams I watch though, because I'm a twitch turbo subscriber and I don't get ads on any channels, and all TTV LOL PRO does in that case is severely slow down the Twitch site.

**Comment by zGato** [comment]
I don't see the point of using TTV LOL PRO whilst being a Turbo sub, even if you're doing it to circumvent a ban. People would rather pay as little as $1 USD in a proxy than paying for Turbo, IMO.
This extension relies on proxies, and you seem to be using the public ones so it's expected for them to not be as fast as hosting or using the restricted ones. And TTV LOL PRO doesn't proxy the website itself by default, so you must have changed your passport level for some reason.

I'll tag @younesaassila as maybe he's interested into implementing this, however, I see it as a very useless feature IMHO.

**Comment by younesaassila** [comment]
I think there are anonymous Twitch viewer extensions to be able to watch streams you're banned from.

Using TTV LOL PRO to not get ads on specific channels is definitely a niche use case. I'm not against implementing it but this is not a priority and can't guarantee it would come anytime soon

**Comment by kurtdh** [comment]
> I think there are anonymous Twitch viewer extensions to be able to watch streams you're banned from.
> 
> Using TTV LOL PRO to not get ads on specific channels is definitely a niche use case. I'm not against implementing it but this is not a priority and can't guarantee it would come anytime soon

There are, but they aren’t compatible with your addon. For example, Twitch anti ban uses an alternate player (not the default Twitch player), and so the proxies do not work on this player (I’ve tried). That’s why I have to watch these channels while I’m logged out, so that it uses the default Twitch player.

**Comment by kurtdh** [comment]
> I don't see the point of using TTV LOL PRO whilst being a Turbo sub, even if you're doing it to circumvent a ban. People would rather pay as little as $1 USD in a proxy than paying for Turbo, IMO. This extension relies on proxies, and you seem to be using the public ones so it's expected for them to not be as fast as hosting or using the restricted ones. And TTV LOL PRO doesn't proxy the website itself by default, so you must have changed your passport level for some reason.
> 
> I'll tag @younesaassila as maybe he's interested into implementing this, however, I see it as a very useless feature IMHO.

I’m your average user, which means I know nothing about proxies or how to use or host them.  With that being said, the default proxy has been working just fine for me on Twitch.tv. 

The reason I subscribe to Turbo is because I use Twitchtheater.tv, and turbo is compatible with this website. Unfortunately, this addon is not, so I have to use Twitch turbo.

**Comment by zGato** [comment]
> I’m your average user, which means I know nothing about proxies or how to use or host them.  With that being said, the default proxy has been working just fine for me on Twitch.tv. 
> 
> The reason I subscribe to Turbo is because I use Twitchtheater.tv, and turbo is compatible with this website. Unfortunately, this addon is not, so I have to use Twitch turbo. 

We don't really have an easy way to make it compatible, it uses a different player which serves ads based on that, so user location/proxies don't make a difference.

However if Turbo is worth it for you and you're fine with it then perfect.

**Comment by kurtdh** [comment]
> > I’m your average user, which means I know nothing about proxies or how to use or host them.  With that being said, the default proxy has been working just fine for me on Twitch.tv.
> > The reason I subscribe to Turbo is because I use Twitchtheater.tv, and turbo is compatible with this website. Unfortunately, this addon is not, so I have to use Twitch turbo.
> 
> We don't really have an easy way to make it compatible, it uses a different player which serves ads based on that, so user location/proxies don't make a difference.
> 
> However if Turbo is worth it for you and you're fine with it then perfect.

Oh I know, because I had a previous post about it where I was told that. You didn’t understand why anybody would use turbo when they could use this add on instead, so I was just explaining to you why I have to use turbo. But then for the few streams I am banned from, this addon would be extremely useful.

**Comment by zGato** [comment]
> Oh I know, because I had a previous post about it where I was told that. You didn’t understand why anybody would use turbo when they could use this add on instead, so I was just explaining to you why I have to use turbo. But then for the few streams I am banned from, this addon would be extremely useful.

Didn't know you were the one that requested that, okay.
I mean, IMO the Turbo price tag is not worth it, even if you can use sites like multitwitch.tv. I would rather create custom layouts with PowerToys FancyZones for example which basically does the same thing but a little bit more inconvenient.

**Comment by kurtdh** [comment]
> > Oh I know, because I had a previous post about it where I was told that. You didn’t understand why anybody would use turbo when they could use this add on instead, so I was just explaining to you why I have to use turbo. But then for the few streams I am banned from, this addon would be extremely useful.
> 
> Didn't know you were the one that requested that, okay. I mean, IMO the Turbo price tag is not worth it, even if you can use sites like multitwitch.tv. I would rather create custom layouts with PowerToys FancyZones for example which basically does the same thing but a little bit more inconvenient.

I would be surprised if FancyZones would have the same capabilities as twitchtheater.tv. I can pause all streams at once. I can turn on all volume at once, or off. I can make specific streams visible or invisible at the click of a button, etc. The most important feature of all to me is the ability to change the quality/resolution of all streams at once as well, otherwise they get set to auto and end up looking terrible. All of these features I've come to rely on over the past couple of years.

**Comment by zGato** [comment]
> I would be surprised if FancyZones would have the same capabilities as twitchtheater.tv. I can pause all streams at once. I can turn on all volume at once, or off. I can make specific streams visible or invisible at the click of a button, etc. The most important feature of all to me is the ability to change the quality/resolution of all streams at once as well, otherwise they get set to auto and end up looking terrible. All of these features I've come to rely on over the past couple of years.

No, it will just make a perfect layout that you can toggle when you want to and then you move your twitch tabs to it, so you get like the twitchtheater.tv, it's not designed to be twitch specific.
However you don't pay Turbo pricing, you get Twitch web client (as you're not embedding the stream and still using your normal or alternative browser) and you won't have the need to change resolution as it will be set to whatever you set on Twitch's main page always.

It's an alternative, twitchtheater will always have more features.
