### ISSUE TITLE
Hello, As of today this extension prevents the video player to work

### ISSUE THREAD

**Issue by Reny900** [younesaassila/ttv-lol-pro#327]
**Describe the bug**
Im not sure when, but today the video player returned error 2k on every stream, no matter the ads or the creator i was trying to watch

**To Reproduce**
Steps to reproduce the behavior: click on any active stream, stream seems to load for a lot of time, then the error 2k shows

**Expected behavior**
Click on a stream and start watching

**Screenshots**

**Desktop 
Nome dispositivo	DESKTOP-Renato
Processore	AMD Ryzen 5 2600 Six-Core Processor               3.39 GHz
RAM installata	16,0 GB
ID dispositivo	E8A4D504-FBFA-4441-BCF3-02E6C089ABD8
ID prodotto	00330-80000-00000-AA644
Tipo sistema	Sistema operativo a 64 bit, processore basato su x64
Penna e tocco	Nessun input penna o tocco disponibile per questo schermo

- Browser  mozilla firefox version 
- Version 
![image](https://github.com/younesaassila/ttv-lol-pro/assets/19189602/555e79da-5624-4b71-b043-15f96a934a2e)
 

**Additional context**

**Comment by jimbo1111** [comment]
Same, getting 2k error in every stream with Brave, but with Firefox developer edition it just shows the circular "loading" graphic and/or a black screen forever, never actually loading the video. Have tried turning on various passport levels and turning anonymous mode on/off and none of this works. When on diplomatic mode, it says "the proxy server is refusing connections"

So, feels like a proxy issue to me?

**Comment by zGato** [comment]
There's an ongoing issue with the public proxies.
https://status.perfprod.com/incident/372178
