### ISSUE TITLE
No longer working on newest Firefox on Mac

### ISSUE THREAD

**Issue by djg007** [younesaassila/ttv-lol-pro#328]
As of today on the newest version of Firefox on Mac, TTV Lol Pro no longer works. When I try to open a stream, all I get is a black screen and a constant loading icon. Anyone else having issues?

**Comment by major-minor-patch** [comment]
Yeah, having the same issue, I'm in Windows though, using Firefox dev edition.

**Comment by Eeems** [comment]
Same issue on linux

**Comment by bickless** [comment]
hi i remove the proxy port and was able to watch and still have no ads hope it helps and is a quick fix for now

**Comment by djg007** [comment]
> hi i remove the proxy port and was able to watch and still have no ads hope it helps and is a quick fix for now

Loaded up the stream for maybe 5-10 seconds then immediate ads for me.

**Comment by MadMeeper** [comment]
Same, Firefox on MacOS not currently working.

**Comment by zGato** [comment]
There was a DDoS attack aimed to the whole DC.
https://status.perfprod.com/incident/372178

Everything should be online right now.
