### ISSUE TITLE
Twitch Drops don't work anymore

### ISSUE THREAD

**Issue by juliocoliveira** [younesaassila/ttv-lol-pro#329]
With this extension enabled, I can't get twitch drops progress anymore.
Same seems to happen with Vaft Script (https://github.com/pixeltris/TwitchAdSolutions/issues/248, https://github.com/pixeltris/TwitchAdSolutions/issues/247).
Can you please take a look at it?

**Comment by zGato** [comment]
Thank you for not bothering to follow the nice template. As I have no information, I'll skip. If Younes wants to debug, it's up to him, as drops work just fine for me.

**Comment by younesaassila** [comment]
@zGato It's okay, Julio is a long  time user of the extension and has helped with the betas.

@juliocoliveira IIRC we tested drops a while back (like 1-2 months ago) and they worked fine (even with Anonymous mode). However lately I've seen more people reporting issues so Twitch might have changed something. I'll see if there's issues on my end and report back when I have a little time to allocate to the project

**Comment by juliocoliveira** [comment]
Yes, take a look when you got the time.
In my tests v1 and v2 don't progress with drops when enabled.

**Comment by zp** [comment]
From my brief testing, it seems like twitch now checks the token/sig/session_id (not sure the exact combo) sent to the **usher.ttvnw.net/api/channel/hls/channel.m3u8** api to acknowledge that you're actually watching a stream for drops to progress on your account

Noticed this with various other proxy based blockers that forcefully remove those for 'strict' anonymous mode, if I uncheck anon mode in ttvlol pro then drops start functioning as they should.

**Comment by zGato** [comment]
> From my brief testing, it seems like twitch now checks the token/sig/session_id (not sure the exact combo) sent to the **usher.ttvnw.net/api/channel/hls/channel.m3u8** api to acknowledge that you're actually watching a stream for drops to progress on your account
> 
> Noticed this with various other proxy based blockers that forcefully remove those for 'strict' anonymous mode, if I uncheck anon mode in ttvlol pro then drops start functioning as they should.

Could be related to this: https://x.com/TwitchSupport/status/1792662211665473680
However, from my test (just done in xQc with the Rust drops) drops progress just fine whilst using Anonymous mode.

**Comment by Dogmentation** [comment]
I was having the same problem with twitch drops not progressing, and I can confirm that unchecking Anonymous Mode resolved the issue for me on 2.3.7.

**Comment by rockerBOO** [comment]
Have been having drops not working for the last 25 days and unchecking Anonymous mode resolved the issue. I do block a bunch of scripts on the page (noscript) as well as ublock if that is relevant.

**Comment by younesaassila** [comment]
Tried to get Pubg drops but they are not working (anonymous on or off) so have no idea. I can add a disclaimer under the Anonymous mode option that "Some users might not be able to get Drops while this is enabled"

**Comment by EnjoyGamesDev** [comment]
I can confirm that disabling anonymous mode worked for me and now my drops progress works normally.

**Comment by juliocoliveira** [comment]
For me with anon mode turned off I can get the drops.

**Comment by QuentinMoss** [comment]
@zGato man you sound salty

**Comment by younesaassila** [comment]
I've clarified the Anonymous option description for the next update (2.3.8). The fix is indeed to disable Anonymous mode while waiting for Drops. Closing this issue

**Comment by ayylmaogod** [comment]
> Thank you for not bothering to follow the nice template. As I have no information, I'll skip. If Younes wants to debug, it's up to him, as drops work just fine for me.

Morons like you is why we can't have nice things. If you don't wanna help just piss off. Like what more do you expect them to give? Drops just don't work that's literally it. Other people were helpful to point out anonymous mode was the issue. Maybe try learning from them next time.
