### ISSUE TITLE
Proxy does not work in Edge, but works in Firefox?

### ISSUE THREAD

**Issue by lightningHoneypot** [younesaassila/ttv-lol-pro#330]
**Debug Info**
Extension: TTV LOL PRO v2.3.7 (normal)
Browser: Microsoft Edge 125.0.0.0 (Windows NT 10.0)
Options:
- Passport level: 2
- Anonymous mode: true
- Using optimized proxies: ["chromium.api.cdn-perfprod.com"]
Channel name: moistcr1tikal
Stream status:
- Proxied: 0, Not proxied: 21
- Proxy: N/A
- Country: N/A
Proxy level of control: controllable_by_this_extension

**Debug Info**
Extension: TTV LOL PRO v2.3.7 (normal)
Browser: Firefox 126.0 (Windows NT 10.0)
Options:
- Passport level: 0
- Anonymous mode: true
- Using optimized proxies: ["firefox.api.cdn-perfprod.com"]
Channel name: moistcr1tikal
Stream status:
- Proxied: 3, Not proxied: 5
- Proxy: firefox.api.cdn-perfprod.com
- Country: RU
Latest ad log entry: {"adType":"preroll","isPurpleScreen":true,"proxy":"firefox.api.cdn-perfprod.com:2023","channel":"moistcr1tikal","passportLevel":0,"anonymousMode":true,"timestamp":1716440296119,"videoWeaverHost":"video-weaver.fra05.hls.ttvnw.net"}

**Comment by zGato** [comment]
Chromium public proxy should now be available, apologies for the downtime, the server was not setup properly and since yesterday that went down, the proxy didn't start up automatically.
