### ISSUE TITLE
infinite buffering

### ISSUE THREAD

**Issue by Robotcircus1** [younesaassila/ttv-lol-pro#336]
when ttv-lol-pro is enabled, twitch streams will infinitely buffer

**To Reproduce**
1. enable ttv-lol-pro
2. try to enter stream

**Expected behavior**
the stream starts up

**Screenshots**

**Desktop (please complete the following information):**

- OS: CachyOs
- Browser firefox
- Version 2.3.7

**Comment by PlayfulPiano** [comment]
Can confirm this experience as well, started today. 2.3.7 firefox on w10

**Comment by zGato** [comment]
https://github.com/younesaassila/ttv-lol-pro/issues/335
