### ISSUE TITLE
Detection during sponsored stream

### ISSUE THREAD

**Issue by SakhG** [younesaassila/ttv-lol-pro#337]
**What**
A message appears over black screen, blocking the stream playback

**When**

this occured during crunchyroll sponsored anime watchalong on channel `https://www.twitch.tv/disguisedtoast`

<details><summary>Screenshots</summary>
  
![image](https://github.com/younesaassila/ttv-lol-pro/assets/10335530/22fafb2a-d591-479c-8dec-7cfb8161a719)
</details>

**Desktop (please complete the following information):**

- OS: Win 10 LTSC 21H2 19044
- Browser: Firefox 127.0.2
- Extension: v2.3.7

**Additional Notes**

this doesn't happen during any other ordinary stream

**Comment by zGato** [comment]
We're not a bypass service/extension. As stated in the wiki, using public proxies you risk Twitch knowing you 100% are using a proxy/VPN service to bypass ads/geolocation restrictions/others.

Use your own proxy in a region that supports watching that streamer specifically and/or that Twitch doesn't detect as being a VPN/proxy. You can check that by testing different proxies with that streamer even if he's offline by just hard refreshing your page and checking if the m3u8 usher request gives 404 (should be fine) or 403 (no no)
