### ISSUE TITLE
Free proxies are randomly asking for username and password

### ISSUE THREAD

**Issue by goodspark** [younesaassila/ttv-lol-pro#338]
**Describe the bug**
Free proxies are randomly asking for username and password

**To Reproduce**

1. Use free proxy (`firefox.api.cdn-perfprod.com:2023`)
2. Watch a stream for a bit
3. Eventually the popup appears and the stream video stops.

**Expected behavior**
This pop-up shouldn't appear

**Screenshots**
![image](https://github.com/younesaassila/ttv-lol-pro/assets/29210237/d5c25345-6595-48ca-88ca-53910603d156)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Firefox 127.0.2
- Extension version 2.3.7

**Additional context**
If I close the popup without entering anything, the streams continue.

Seems related to https://github.com/younesaassila/ttv-lol-pro/issues/160 but I'm not using a reserved proxy.

**Comment by zGato** [comment]
Should be fixed now. This is not an extension-wise issue, but the authentication service somehow dies after some time and then as the load balancer can't authenticate himself to the proxy, it asks the client for credentials.

**Comment by goodspark** [comment]
Thanks for the explanation!
