### ISSUE TITLE
Add a way to export/import settings

### ISSUE THREAD

**Issue by younesaassila** [younesaassila/ttv-lol-pro#34]
Chrome big poopoo -- if update not done correctly all settings can get cleared due to different ID being used for extension.
Export/Import settings option would be nice. Also perhaps update "update notification banner" to include suggestion to backup settings?

**Comment by thinkpad4** [comment]
I too would like this option

**Comment by thinkpad4** [comment]
YES YES YES, you've made a perfect extension even better.  Now I can copy my settings to different browsers quickly when testing things or whatever  Thank you
