### ISSUE TITLE
ads getting trough, stream freezing

### ISSUE THREAD

**Issue by adorhun** [younesaassila/ttv-lol-pro#342]
**Describe the bug**
streams get stuck buffering, ads play when paused and resumed.
proxy shows idle in addon window

**To Reproduce**

1. Go to '(https://www.twitch.tv/piratesoftware)', cohhcarnage
proxy slider on middle

**Expected behavior**
seamless stream, ad counter in the corner

**Screenshots**
![ttv idle](https://github.com/user-attachments/assets/fad68e07-a8d0-4927-8aa9-74c49aad1299)

![ttv proxy st](https://github.com/user-attachments/assets/3545ead8-ad38-42a7-a4ce-3ca4bf085246)

**Desktop (please complete the following information):**

- OS: W10
- Browser mozilla
- Version 128.0.2 

**Additional context**

**Comment by iNfz** [comment]
same problem here. ads getting trough.
firefox 128.0.3
win11

**Comment by djg007** [comment]
Not sure to create a new thread or add on to this one. But, ads are getting through and freezing the stream. I'm using 2.3.10 with Firefox on MacOS.

**Comment by mugmonster** [comment]
not currently getting any freezing, but ads are definitely getting through

**Comment by djg007** [comment]
> not currently getting any freezing, but ads are definitely getting through

When it freezes I get the overlay at the top that says "so and so is taking an ad break; stick around to support the stream!". Sometimes the stream still plays but has a brief interruption by an ad and other times it freezes the stream until you refresh.
