### ISSUE TITLE
Streams no longer loading in Firefox on Mac

### ISSUE THREAD

**Issue by djg007** [younesaassila/ttv-lol-pro#343]
Currently using 128.0.3 Firefox on Mac. When I try to load a stream, I get a black screen with the loading animation going for a few minutes until it turns into a 2000 Error. Anyone else having this issue?

**Comment by jack-worman** [comment]
Same here

**Comment by Asubatsu** [comment]
I am also having this issue, I've been able to get it to work by pausing and un-pausing repeatedly the last two days.  But as of today, nothing stops the black screen with a loading circle.  I do not get the 2000 error  so far, just infinite loading circle and black screen.

Edit: I'm currently using Firefox version 126 on Windows.
Perfprod shows nothing is down or experiencing issues.

**Comment by MadMeeper** [comment]
Also experiencing this issue for the past couple days!

**Comment by Sumpsen** [comment]
I am also having issues as of today on Windows with Firefox version 129.0. I receive a black screen and no matter how many times I pause/refresh, the stream never loads. 

As soon as I disable the extension, issue goes away. I also tried with ONLY this extension enabled and the problem persisted.

**Comment by BumFellow** [comment]
Same deal here except i noticed that only the pop out player works while the extension is active.

**Comment by Asubatsu** [comment]
> Same deal here except i noticed that only the pop out player works while the extension is active.

Is the popout player a Twitch feature or a Browser/addon feature?

**Comment by zigzter** [comment]
Same here, Firefox 129.0 on Arch. I also noticed the feature to whitelist the current stream doesn't appear unless they're already whitelisted.

**Comment by ape-manque** [comment]
Yeah having the same issue, perpetual black loading screen. Firefox 129.0 on Windows 10. Only popout player works.

**Comment by Asubatsu** [comment]
> Same deal here except i noticed that only the pop out player works while the extension is active.

This works to see the stream with the addon turned on, however you still get ads.

**Comment by Firsh** [comment]
Also on Chrome, Windows 11

**Comment by MichalLechowski** [comment]
I very often get long loading time when I open any stream, so my suggestion is to try just waiting, for me sometimes it takes even 40-50 seconds for a stream to start. It's annoying, but it always works sooner or later. Maybe you are just pausing and starting or refreshing the page too soon. But I sure wish it'd load faster, sometimes it does, but rather rarely.

Firefox 129.0.1
W11
