### ISSUE TITLE
Streams no longer loading on Firefox (similar to the August 5th report)

### ISSUE THREAD

**Issue by Asubatsu** [younesaassila/ttv-lol-pro#349]
**Describe the bug**
Like the August 5th report, opening any stream is met with a black screen and infinite loading circle in the center.  Perfprod does not show anything being busy or down.

**To Reproduce**

1. Go to Twitch.tv
2. Click on any currently live stream
3. Wait for webpage to load
4. See that the the UI is loaded successfully, but the player remains in a perpetual loading animation

**Expected behavior**
After a brief delay/loading time it is expected that the stream will successfully display without ads.

Screenshot:
![image](https://github.com/user-attachments/assets/8d0b5f7d-9d77-418f-b244-bd7631b821a7)

(not sure if that screen grab will work, I've not made one of these before.)
**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox
- Version 126.0 (64bit)

**Additional context**
This is identical to an issue/bug report from August 5th.  Don't know what ended up being the solution to it, but the bug was fixed within a few days and the bug report was moved to resolved.

**Comment by djg007** [comment]
Dealing with the same issue using Firefox on Mac.

**Comment by zGato** [comment]
https://status.perfprod.com/incident/432981

**Comment by Asubatsu** [comment]
Guess it takes some time for Perfprod to show/update status issues.  I must have run into it right as it was beginning to happen.  

I definitely checked when I first started getting issues and didn't see any status issues on there.

**Comment by tugofwardolphin52** [comment]
I'm having the same issues. Stream was working fine until the channel ended around 8pm Pacific then we went into a different channel through a raid only for that new channel to start having issues loading. I eventually closed it and came back a few minutes ago to watch someone I'm following go live only to be met with the same issue. My OS is Windows 10 and browser is Firefox.

**Comment by zGato** [comment]
> Guess it takes some time for Perfprod to show/update status issues. I must have run into it right as it was beginning to happen.
> 
> I definitely checked when I first started getting issues and didn't see any status issues on there.

Not your fault, status page is not accurate due to how the infra is built.

**Comment by zGato** [comment]
As per my provider, the server was locked by accident and is now unlocked.
I will restart every proxy instance in roughly 10 minutes, once that's done, servers will become available.

Apologies for the long downtime, will work on improving by adding several edge servers in the future.
https://status.perfprod.com/incident/432981
