### ISSUE TITLE
[Feedback] Does Not Work As Advertised (Commercial Break in Progress)

### ISSUE THREAD

**Issue by JCollins2048** [younesaassila/ttv-lol-pro#351]
First and foremost, I want to tell anyone reading this the following:

### Using the default proxies will more than likely provide a *less-than-desirable experience*.<br>You need to *use your own proxies* to get the most out of this extension.

This was pointed out to me by someone over on a somewhat related repository and, I believe, has been mentioned in a few different Play Store reviews.  And that kind of *irks* me.  If this add-on is best utilized via user-made proxies, then why not *say so* in the instructions, somewhere?

From my understanding, everyone who downloads this ends up using the same default proxy settings, thus the servers are constantly at capacity.  This, in turn, leads to advertisements being replaced by "commercial break in progress" windows rather than actual adverts, but the 30-second delay remains.  While this is arguably a step up from the inane things that *do* play during *Twitch* commercial breaks, this still *isn't* providing most users with the features or functions they expect right out of the box — myself included.

This is less of a proper "extension" and more of a "do-it-yourself" project, in my opinion.  The extension specifies that fiddling with the settings won't help if a user is getting "commercial break in progress" errors.  It should also specify that it's **encouraged** that users provide their own proxies.  Otherwise, you get ignorant people like me storming your front door and leaving 1-star reviews of your product.

Just some food for thought.  Thank you for your time.

**Comment by zGato** [comment]
Do we advertise somewhere that free and public proxies are provided?
No, those are a bonus, provided as courtesy.

This is a proxy-based solution, just by reading the first 3 paragraphs of the extension description you will know, thus, you need proxies to make it work.
The extension's source is here, and has the methods to have an ad-free experience at Twitch, but as it's proxy-based, needs proxies. It's as clear as water.

The wiki (which is linked in the extension's dropdown and description) explains everything you're complaining about.

Lastly, this is not a product, anyone can keep throwing 1 star reviews, I personally don't care anymore.
