### ISSUE TITLE
Ads getting through and freezing when they do

### ISSUE THREAD

**Issue by djg007** [younesaassila/ttv-lol-pro#352]
Using the newest Firefox on MacOS Sonoma 14.5. Ads are getting through on 2.3.10 and when they do, they'll freeze on a still frame until you refresh or reset player. That doesn't work though since it just refreshes the ad.

**Comment by iNfz** [comment]
it's been a thing for months. This extension is completely useless

**Comment by zGato** [comment]
> it's been a thing for months. This extension is completely useless

That's why it has over 1.6k simultaneous users currently using the public proxies + a bunch of people with their own proxy or using our restricted infra
![image](https://github.com/user-attachments/assets/a76ac264-8cf9-4403-b4d9-d63c96aa9739)

**Comment by iNfz** [comment]
installed extension != working extensions.

**Comment by zGato** [comment]
> installed extension != working extensions.

over 60k installations in Chrome and 30k in FF, do you know the difference between installations and current connections to the proxy that the extension uses by default?

**Comment by iNfz** [comment]
ok..

**Comment by CodeMeZone** [comment]
> > installed extension != working extensions.
> 
> over 60k installations in Chrome and 30k in FF, do you know the difference between installations and current connections to the proxy that the extension uses by default?

Why do you have to flex numbers, that's funny.

**Comment by zGato** [comment]
> > > installed extension != working extensions.
> > 
> > 
> > over 60k installations in Chrome and 30k in FF, do you know the difference between installations and current connections to the proxy that the extension uses by default?
> 
> Why do you have to flex numbers, that's funny.

Flexing numbers what? my screenshot showed 1.6k users, nowhere near 60k or 30k, that's why I commented that, since the other dude though that was installations.
