### ISSUE TITLE
Black screen on stream load 90% of the time

### ISSUE THREAD

**Issue by Aerasyn** [younesaassila/ttv-lol-pro#353]
**Describe the bug**
Black screen when opening most streams as of today 10/30/24. A couple streams load but it might be ones that arent running ads. If I disable the addon, the video runs as normal with ads.

**To Reproduce**
Open a few streams

**Expected behavior**
Usual behavior of blurring video if ad is running, but still playing stream.

**Screenshots**
![image](https://github.com/user-attachments/assets/464e718a-6a5f-4253-80d3-6ace4f4d7aaa)

**Desktop (please complete the following information):**

- OS: Windows 11 24H2
- Browser Firefox v131.0.3
- Version of addon: 2.3.10

**Comment by Aerasyn** [comment]
Hmm, well I updated to firefox 132 and some streams that wouldnt open now open, but others are still not loading. :\

**Comment by Aurigium** [comment]
Same problem here.

    OS: Windows 11 24H2
    Browser Firefox v132.
    Version of addon: 2.3.10

**Comment by Cazed** [comment]
Same issue here. Seems to have started happening within the past few days.

**Comment by zGato** [comment]
Should be temporarily fixed now. Do not spam requests, and you'll get the stream just fine. Do not switch over streamers too fast either.
