### ISSUE TITLE
Blocked\Detected on one particular channel

### ISSUE THREAD

**Issue by BumFellow** [younesaassila/ttv-lol-pro#354]
**Describe the bug**
A proxy or unblocker has been detected. This premium content will not be available to you while it is in use. (Error #3)

**To Reproduce**
go to https://www.twitch.tv/tokushoutsu

I have Anonymous mode on and passport set to official with no other settings changed or proxies added

**Expected behavior**
To be able to view the channel with the usual performance i've experienced with this enabled

**Screenshots**
![blocked](https://github.com/user-attachments/assets/f149f28b-d02c-49ca-80f7-9b03299d5799)

**Desktop (please complete the following information):**

- OS: Windows 10 pro 22H2
- Browser Firefox
- Version 132.0 (64-bit)

**Additional context**
I'll try disabling other plugins to check but thought i'd bring this up here just in case

**Comment by zGato** [comment]
There's not really an easy way to bypass these. We use proxy based solutions and those have some limitations. Public proxies are 100% flagged as proxies on Twitch's end, thus, if the streamer geoblocks some countries or only whitelists a few, you'll get that banner.

You need to figure out which country isn't blocked and get a residential proxy there, and hopefully they whitelist ad-free countries. But most don't.

**Comment by BumFellow** [comment]
Ahh, I gotchya. Thought I'd bring this up just in case it was something else.
