### ISSUE TITLE
Extension makes all streams load for like 2 minutes

### ISSUE THREAD

**Issue by vatum20** [younesaassila/ttv-lol-pro#357]
**Describe the bug**
After choosing any stream, it loads for around 2 minutes before it loads. Sometimes even longer. It doesn't happen when I turn the extension off.

**To Reproduce**

1. Go to 'twitch.tv'
2. Click on any stream
3. It's loading for a long time

**Expected behavior**
It loads quickly

**Screenshots**
I don't think screenshot is required

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- Browser: both Brave and Opera GX
- Version: 2.3.10

**Comment by Cyarutchiii** [comment]
@zGato I'd love to know if you told me how this was completed? I still have this problem. It's only on OperaGX and Brave, not on Chrome.
