### ISSUE TITLE
Has this stopped working?

### ISSUE THREAD

**Issue by lucas-morais27** [younesaassila/ttv-lol-pro#358]
**Describe the bug**
The ad blocker has stopped working in Google Chrome. When trying to stream, it either freezes the stream or displays a black screen that loops indefinitely.

**To Reproduce**

1. Open Google Chrome.
2. Navigate to a streaming website where the ad blocker is active.
3. Attempt to start a stream.
4. Observe the issue: the stream either freezes or displays a black screen.

**Expected behavior**
The ad blocker should function correctly without interfering with the streaming experience, allowing the stream to play as expected.

**Screenshots**
![image](https://github.com/user-attachments/assets/a770bbea-692f-4e35-922b-5b583d498aa4)

**Desktop (please complete the following information):**

- Browser: Google Chrome

**Comment by Weldoret** [comment]
Can confirm this also happens on Firefox.

**Comment by ZephWasTaken** [comment]
Can confirm, also happening on Opera browser.

**Comment by Kroetelp** [comment]
they must have changed something like 3-4days ago it was working fine and then boom the next time i clicked on another streamer it kept buffering until i deactivated that plugin, is there any working workaround right now?

**Comment by Asubatsu** [comment]
https://status.perfprod.com/

Check this if you ever get any issues.  The public API has been down for 4 days.  I'm not sure what needs to happen to fully fix it, but that is currently causing the issues as far as I can tell.

I would assume the people in charge of some of the infrastructure are probably busy with holidays.  At least I hope that's the case.

**Comment by zGato** [comment]
Apologies for the inconvenience everyone. Should be back up now, applied an experimental patch.
More details & up-to-date info in the official Discord :)
