### ISSUE TITLE
Still getting mid-roll ads

### ISSUE THREAD

**Issue by username0239409j** [younesaassila/ttv-lol-pro#36]
Don't think I've received a pre-roll but sometimes get mid-roll ads using this and ublock origin, I don't think I have any custom filters

**Comment by younesaassila** [comment]
Yeah from what I've been told Twitch changed how they serve ads and now even if an IP is from a country without ads, after so many requests from that IP they'll get ads even if from a country without ads.
I'm trying to implement #32 to (hopefully) mitigate this
