### ISSUE TITLE
Release CRX-file to make Chromium based browser to autoupdate.

### ISSUE THREAD

**Issue by dpthegrey** [younesaassila/ttv-lol-pro#39]
Allow users to install .crx file of the extension to auto update the extension in chromium based browser.

**Comment by younesaassila** [comment]
Hey, I tried to switch to a `CRX` extension for Chrome for v1.5.0, but unfortunately `CRX` extensions disable themselves after one browser restart if they are not installed from the Chrome Web Store :/

**Comment by dpthegrey** [comment]
maybe I can help with that auto disable thing, We need to add extension (crx) to allowlist

**Comment by younesaassila** [comment]
Thanks for your email, indeed it appears this could work with some Registry tweaks.

References:
- https://gitlab.com/magnolia1234/bypass-paywalls-chrome-clean/-/tree/master/allowlist

I don't really want to work on this right now so anyone who wants to is welcome to do so!

**Comment by TheRayJohnson** [comment]
This would be sweet if someone can work on this in the new year!

Or maybe make a lightweight newsletter kind of thing using something like Sendinblue, Mailjet or Mailchimp (free tiers) and send a short and sweet email of update? But that's a lot of work to remember to send email, collect users data (name/email) so I suspect the best option is GitHub alerts.

**Do this directly via GitHub**.
Go to a [project page](https://github.com/younesaassila/ttv-lol-pro) and click Watch button in the top right corner. There's a Custom option where you can toggle Releases. (Free free to include this in the README.md lol)

Or consider [newreleases](https://newreleases.io) and [Gitpunch](https://gitpunch.com).

**Comment by younesaassila** [comment]
Okay so I've successfully installed the CRX version of the extension using the ExtensionAllowlist registry tweak. I wonder if people would be willing to execute a .reg file as admin though... I feel like we'd have to continue to provide a ZIP version. Also I haven't tested the auto-update aspect, let's hope Chrome isn't a b*tch and works like it's supposed to (simple XML file hosted on this repo with GitHub Pages)

Seems like the biggest part of the work is writing new Installation docs

**Comment by younesaassila** [comment]
![Screenshot](https://user-images.githubusercontent.com/47226184/210072633-b5e8817f-00b5-4d5a-bade-f25b55b3be2d.png)
👀

**Comment by younesaassila** [comment]
Spent my entire day trying to implement auto-update. Everything is supposed to work, yet Chrome refuses to update the extension. I have no idea why.

I'm done trying to add this. Let's hope the project gets upstreamed by the TTV LOL team so that they can deliver updates via the Chrome Web Store. Google makes everything so complicated for those that dare not to upload their extension to their store.

If anyone wants to attempt to implement this, GOOD LUCK.

**Comment by revunix** [comment]
Currently, I use the Arc Browser, this allows the installation of CRX files. I would also like to benefit from an automatic updater.

**Comment by Delphox** [comment]
@younesaassila Hello, I just did a test on my repo and successfully updated it (both on Chromium and Kiwi Browwser).

https://user-images.githubusercontent.com/5883538/212785108-a2e0121e-3a61-4d1f-acd2-0ca9481d3113.mp4

[Here's my xml file](https://github.com/Delphox/ttv-lol-pro/blob/main/update.xml)

And [here's the test releases](https://github.com/Delphox/ttv-lol-pro/releases) they point to. They're the same as your 1.6.0 and 1.6.1 except with `"update_url":"https://raw.githubusercontent.com/Delphox/ttv-lol-pro/main/update.xml"` added in the (minified) manifest.json. So you should be able to do the same thing just replacing with your own extension id and respective raw repo path.

**Comment by younesaassila** [comment]
@Delphox Thanks for your comment. I finally figured out what I was doing wrong: I thought the XML file could contain a history of updates just like Firefox allows, but turns out Chrome expects to only see the latest version. Fixed it.

Next update will have Chrome auto-update available
