### ISSUE TITLE
Purple Adblock Support

### ISSUE THREAD

**Issue by revunix** [younesaassila/ttv-lol-pro#46]
Is it possible to use the servers of [Purple Adblock](https://github.com/arthurbolsoni/Purple-adblock)?

https://eu1.jupter.ga/channel/{channelname}
https://eu2.jupter.ga/channel/{channelname}

This server a working very good.

**Comment by younesaassila** [comment]
TTV LOL PRO is only compatible with servers using the same structure as TTV LOL's API (`/ping`, `/playlist`, and `/vod` routes).

I don't know if Purple Adblock is compatible with this structure. If it is and you want to use it, just add its URL to Options > Proxies.
