### ISSUE TITLE
Page refreshes when pausing VODs

### ISSUE THREAD

**Issue by DAmNRelentless** [younesaassila/ttv-lol-pro#47]
The page is automatically refreshed by the extension when a VOD is being paused for around 30 seconds which is very annoying.
Version 1.6.1

**Comment by younesaassila** [comment]
The page is refreshed or just the player?

**Comment by younesaassila** [comment]
Am not able to reproduce. Can you give a bit more context? Were you watching the VOD for a while and then paused it? Is the player refreshing or the whole page? Have you tried disabling the "Reset player on midroll" feature? What browser are you using?

**Comment by DAmNRelentless** [comment]
After a bit more testing, it turns out this is caused by another extension I overlooked before. Sorry.
