### ISSUE TITLE
Prerolls happens if you jump from a channel to another

### ISSUE THREAD

**Issue by TsukiZero** [younesaassila/ttv-lol-pro#52]
Prerolls at least seems to happen if you jump directly from a channel to another (like through a raid, or by clicking to watch a channel when the notification they have gone live happens).

**Comment by younesaassila** [comment]
You can try to use other proxies listed here: #37

**Comment by TsukiZero** [comment]
I see no way to change proxies. And I don't think the proxies are the problem here.

**Comment by younesaassila** [comment]
> I see no way to change proxies. And I don't think the proxies are the problem here.

Other proxies can be added in the extension options (accessible via your browser's extensions page).

Proxies are 100% of the problem. The extension only redirects your Twitch requests through proxies to try to avoid ads. TTV LOL's API hasn't worked very well these last few weeks. Perhaps trying out other proxies might get you better results.

**Comment by TsukiZero** [comment]
That's extremely hard to figure, given how hidden the Options submenu is.

**Comment by younesaassila** [comment]
Adding a link to Options in extension popup is planned: #51
