### ISSUE TITLE
CRX REQUIRED PROOF MISSING

### ISSUE THREAD

**Issue by TheRayJohnson** [younesaassila/ttv-lol-pro#58]
Hi,

Chrome error with [1.7.1]([v1.7.1-chrome.crx](https://github.com/younesaassila/ttv-lol-pro/releases/download/v1.7.1/v1.7.1-chrome.crx))

![image](https://user-images.githubusercontent.com/36357206/213519128-d0e02d7b-6e1e-419a-930d-483ca89ae255.png)

**Comment by younesaassila** [comment]
Hi, the CRX file needs to be downloaded via Right-Click -> "Save link as…"

**Comment by TheRayJohnson** [comment]
Yeah, my mistake I already closed this :)

**Comment by younesaassila** [comment]
No problem :) Updated the filename as well to make it clearer
