### ISSUE TITLE
New Chrome .crx automatically disabling

### ISSUE THREAD

**Issue by zaneshaw** [younesaassila/ttv-lol-pro#60]
After following instructions on how to install the new .crx installation of the extension (as well as updating the registry editor with the correct keys/values), Chrome will disable the extension for me for security concerns. Apparently, the only way to fix this is by using the dev/canary branch of Chrome.
Did I miss a step or is something else wrong?

[![image](https://user-images.githubusercontent.com/29834597/213557570-da5f94f9-9f87-4642-967b-e59362a9b8ae.png)](https://support.google.com/chrome/?p=ui_remove_non_cws_extensions&hl=en-US)
![image](https://user-images.githubusercontent.com/29834597/213557878-c0a18b68-5ba6-44ad-a647-f04c55ae03fc.png)

**Comment by younesaassila** [comment]
Have you fully restarted Chrome after modifying the registry?

**Comment by zaneshaw** [comment]
It might've been running in the background (background extensions maybe?). I'll just try ending task.

**Comment by zaneshaw** [comment]
Yeah that was it, sorry. I just closed all the windows instead of restarting. Thanks!
