### ISSUE TITLE
Extension disabled on restart

### ISSUE THREAD

**Issue by Lucas559-noob** [younesaassila/ttv-lol-pro#61]
I'm using edge and followed the steps, found that edge was not on regedit, so I created the stuff and added the last part with the extension id
![image](https://user-images.githubusercontent.com/54007604/213585529-e7121abd-7597-4a1d-a7d8-efda1b6b1736.png)
![image](https://user-images.githubusercontent.com/54007604/213585637-c9650bc1-1461-4105-a086-c1263fcdda44.png)
and now it says someone controls the browser, maybe because the regedit changes
so can someone spot what I did wrong?

**Comment by Lucas559-noob** [comment]
Or maybe it's working, edge just said about an extension installed probably without my knowledge and disabled, but it's enabled

**Comment by younesaassila** [comment]
The top banner saying "Your browser is managed by your organization" is expected. This is caused by the registry changes. It looks like the extension got loaded successfully.
