### ISSUE TITLE
Question: Automatic Updates installation for Opera GX

### ISSUE THREAD

**Issue by Makezu90** [younesaassila/ttv-lol-pro#63]
Hi

There was info how to install with automatic updates and needed change registry things. so im curious how i can do it that for Opera GX? Opera GX has that developer mode setting in extensions page but how registry thing works?

**Comment by younesaassila** [comment]
Couldn't find anything on Google. You can try to use the Registry path for Chrome, if that doesn't work perhaps try with `Opera/Opera` or `Opera Software/Opera Stable`

**Comment by younesaassila** [comment]
After a bit of research, Opera doesn't seem to support policies, thus allowlisting extensions is not possible at the moment.
