### ISSUE TITLE
Stream “pauses” and buffer keeps increasing

### ISSUE THREAD

**Issue by Lucas559-noob** [younesaassila/ttv-lol-pro#64]
Not sure the reason, but for me the video keeps like freezing for 0.2 seconds for a period of time and the buffer keeps increasing. Not sure what causes that, internet can't be the reason since buffer gets like 3 seconds, 8 seconds and increasing. Is this because it's blocking an ad?

**Comment by younesaassila** [comment]
Are you using other Twitch ad blockers? Is the "Reset player on midroll" feature of TTV LOL PRO enabled?

**Comment by Lucas559-noob** [comment]
> Are you using other Twitch ad blockers? Is the "Reset player on midroll" feature of TTV LOL PRO enabled?

I have a DNS enabled, but I think it can't do those stuff, and the reset player on midroll is off

**Comment by younesaassila** [comment]
That's weird. Try to use another proxy in the extension's settings.

**Comment by Lucas559-noob** [comment]
> That's weird. Try to use another proxy in the extension's settings.

Using from Asia, and apparently the same problem.
Looking at advanced info, I can see it started with 5 seconds(even pausing and unpausing it take time to get to load, and never gets a lower time, keeps around 4 and 6 seconds). But I noticed something, every time the stream freezes, the fps goes down(currently it doesn't show) and when stream is back the fps starts from 15 and go up to 60, so I guess the issue is the fps, but it's a device issue then?

**Comment by younesaassila** [comment]
Are you sure the extension is causing this? Does the issue still happen if you disable the extension completely?

**Comment by Lucas559-noob** [comment]
> Are you sure the extension is causing this? Does the issue still happen if you disable the extension completely?

Disabled the extension, buffer, and latency are on a normal time, 2.50 to 3.10 seconds, and no freezes or fps drops.
Also, the same stuff happens on that other extension of a better player for twitch, for me, it goes from 4 seconds to 6 and keep increasing, but that's because it goes to a server and that server sends the stream to me.

**Comment by younesaassila** [comment]
Well the stream is sent from a server depending on the proxy's location, so increased buffer and latency is expected. However I have no clue as to why these two values would keep increasing throughout the stream.

**Comment by Lucas559-noob** [comment]
> Well the stream is sent from a server depending on the proxy's location, so increased buffer and latency is expected. However I have no clue as to why these two values would keep increasing throughout the stream.

Probably is because of the distance to servers? Or twitch or from the proxy, then the response time is bigger, and sometimes it like “disconnects”.

**Comment by younesaassila** [comment]
Yeah but why would the buffer and latency keep increasing though? Have you tried to use another non-proxy ad blocker like [Video Ad-Block for Twitch](https://github.com/cleanlock/VideoAdBlockForTwitch)? It could work better, perhaps

**Comment by Lucas559-noob** [comment]
> Yeah but why would the buffer and latency keep increasing though? Have you tried to use another non-proxy ad blocker like [Video Ad-Block for Twitch](https://github.com/cleanlock/VideoAdBlockForTwitch)? It could work better, perhaps

Used some times ago but switched because it shows the commercial break in progress screen(tested now again and same thing), so people on his server said that ttv lol pro worked for them, better than ttv lol(not sure why)

**Comment by iznawh** [comment]
i am also having the same problem as well

**Comment by ThexUniverse** [comment]
This seems like the closest to what I'm experiencing, which is it buffers, but only when the stream resolution is higher than 480. Usually triggered if I'm either flipping through streams, or if i pause a stream then come back, the latter of which allows an ad to get through.

**Comment by younesaassila** [comment]
To be clear, an increased buffer is expected since the stream is coming from servers farther away from you than normal (i.e. proxying). What this issue is about is a buffer time that keeps increasing throughout the stream (e.g. 1s -> 3s -> 7s -> ...)

**Comment by iznawh** [comment]
Yes, that is what happening for me. It'll go all the way up to 30s+ of delay until I press pause play couple of times

**Comment by younesaassila** [comment]
Is anyone still having this issue?

**Comment by ipsusu** [comment]
I stopped having this issue for a while but It's come back recently in the past few days. Just on a new stream load, it'll buffer then load for a few seconds then buffer again in a loop until I spam refresh or reload the player a few times.

**Comment by LukeWolfGames** [comment]
This happens to me as well.
What I notice first though is after the initial ad from loading the stream, the stream will go black and I have to press the play button / reload the page for it to start running again, and then it buffers a lot for a while before returning to normal. It seems to do this for about as long as an ad runs.

**Comment by Lucas559-noob** [comment]
Decided today to see this again, on console it shows those every time it freezes
![image](https://github.com/younesaassila/ttv-lol-pro/assets/54007604/48b6f456-5a9c-4364-97e7-16c25c141f80)
I think bttv affecting this
