### ISSUE TITLE
Not blocking live ads as of 20th January

### ISSUE THREAD

**Issue by triplesevenbob** [younesaassila/ttv-lol-pro#65]
Hi great app but not working since Friday. I still see pre-roll ads and ads during a stream. I have the fallback servers set and no luck now. Firefox nightly for macos+adblockplus+ttv-lol-pro

**Comment by younesaassila** [comment]
To mitigate midrolls, you can enable the "Reset player on midroll" feature in the extension's options. This feature was previously on by default, which might explain why you're now seeing midrolls.

**Comment by triplesevenbob** [comment]
> To mitigate midrolls, you can enable the "Reset player on midroll" feature in the extension's options. This feature was previously on by default, which might explain why you're now seeing midrolls.

If I enable that, a stream keeps going in a loop starting and stopping and i cannot watch any stream with that feature enabled.

**Comment by younesaassila** [comment]
Are you using the VAFT script? If so, this could be the cause for the infinite loading

**Comment by triplesevenbob** [comment]
> Are you using the VAFT script? If so, this could be the cause for the infinite loading

No, stock addons I wrote the wrong app I am using ublock origin without edits to it, firefox nightly beta for macos, and your extension with the proxies added.

**Comment by younesaassila** [comment]
That's weird, I'll try to see if I can replicate this issue to hopefully improve that feature. For prerolls though, if other proxies aren't doing it I would suggest you try to use other ad blockers (perhaps [Video Ad-Block for Twitch](https://github.com/cleanlock/VideoAdBlockForTwitch) would work better for you?)
