### ISSUE TITLE
Twitch engineers have defeated this as of today. Getting commercial break screen for prerolls and random midrolls

### ISSUE THREAD

**Issue by Proaxel** [younesaassila/ttv-lol-pro#66]
![image](https://user-images.githubusercontent.com/9545347/213887310-6af23b32-386d-40a4-b9f4-8784559ca7fa.png)

**Comment by younesaassila** [comment]
To mitigate midrolls, you can try to enable the "Reset player on midroll" feature in the extension's settings.
For prerolls, you can try to use other proxies compatible with the extension, here are a few recommendations: #37

**Comment by triplesevenbob** [comment]
> To mitigate midrolls, you can try to enable the "Reset player on midroll" feature in the extension's settings. For prerolls, you can try to use other proxies compatible with the extension, here are a few recommendations: #37

I tried every proxy in the post and it does not fix that

**Comment by Proaxel** [comment]
> To mitigate midrolls, you can try to enable the "Reset player on midroll" feature in the extension's settings. For prerolls, you can try to use other proxies compatible with the extension, here are a few recommendations: #37

This actually worked, thanks! Sorry for taking so long to reply I tend to forget to follow up on this stuff a lot

Also where is the settings menu? I accessed it once to add the proxies back then and now I completely forgot

**Comment by younesaassila** [comment]
@Proaxel On Chrome right-click the TTV LOL icon > Options/Preferences.

On Firefox, `about:addons` > TTV LOL PRO > 3 dots > Options/Preferences
