### ISSUE TITLE
Ads are now bleeding through

### ISSUE THREAD

**Issue by TsukiZero** [younesaassila/ttv-lol-pro#67]
With the default proxy at least.

**Comment by younesaassila** [comment]
I know :( 
You can try to use the "Reset player on midroll" feature or try other proxies.
If none of that works, look for another Twitch ad blocker.

I can't do anything about TTV LOL's proxy since I don't manage it.

**Comment by TsukiZero** [comment]
> I know :( You can try to use the "Reset player on midroll" feature or try other proxies. If none of that works, look for another Twitch ad blocker.
> 
> I can't do anything about TTV LOL's proxy since I don't manage it.

Actually, "Reset player on midroll" works even for the "preroll ad bleed"! Maybe it should be on by default with a setting to disable it from the addon button?

**Comment by younesaassila** [comment]
The feature is only supposed to work for midrolls. It used to be enabled by default but because it is incompatible with VAFT, and since a lot of users combine this extension with VAFT, I had to disable it by default.

**Comment by TsukiZero** [comment]
Ah, I see. Although it is working better than VAFT still.
