### ISSUE TITLE
Understanding proxies

### ISSUE THREAD

**Issue by Lucas559-noob** [younesaassila/ttv-lol-pro#68]
I saw another github repo about the proxies https://github.com/AlyoshaVasilieva/luminous-ttv-ext.
And now I was thinking(since I noticed that the free servers are the location and not from where it makes stream ad free). So if I do a math, there is the time to go from my location to server location(idk the exact time since idk how to do a speedtest with proxies, so I will guess 100ms?), the server to Russia(30ms?), Russia to server(same 30ms?) and server back to my pc(100ms?).
If I did the server myself for me, it would be my pc to server(instantly), then to Russia and then back to my server that goes back to my pc.
Or this would affect nothing in speed?

**Comment by younesaassila** [comment]
The proxy is only used for the initial manifest request. Once that is done, Twitch starts streaming directly to your computer, though thinking you live elsewhere.
