### ISSUE TITLE
1.7.1 and uBlock VAFT script conflict

### ISSUE THREAD

**Issue by Nerxxy** [younesaassila/ttv-lol-pro#70]
After updating to 1.7.1 and using uBlock VAFT script whenever there's an ad the stream just goes black screen and loads, never had the issue on 1.7.0.

When I turn off uBlock and refresh the page everything works fine, and same goes for it I leave uBlock on and turn off TTV LOL Pro. Its only when both are enabled that the issue occurs.

If there's any other information u would like to know lmk and ill get on it.

**Comment by younesaassila** [comment]
Is "Reset player on midroll" enabled in TTV LOL PRO's settings? If so, please disable it.

Otherwise, please post a screenshot of the Twitch page's console when that happens (press F12 for the Dev Tools to open, then Console tab). That way I can check if it's an issue caused by TTV LOL PRO.

**Comment by triplesevenbob** [comment]
> Is "Reset player on midroll" enabled in TTV LOL PRO's settings? If so, please disable it.
> 
> Otherwise, please post a screenshot of the Twitch page's console when that happens (press F12 for the Dev Tools to open, then Console tab). That way I can check if it's an issue caused by TTV LOL PRO.

reset player on midroll not enabled.
![error](https://user-images.githubusercontent.com/66889760/215309344-be57e43a-89d9-484d-b428-991aaec7f5e2.jpg)

**Comment by younesaassila** [comment]
@triplesevenbob No errors from TTV LOL PRO on your screenshot, in fact, no initialization message either. Have you scrolled up the console to check for any TTV LOL PRO logs? If there's none it means the extension is not installed properly.

**Comment by triplesevenbob** [comment]
How about now
![error2](https://user-images.githubusercontent.com/66889760/215321712-c66d27a7-6b87-4cef-acfe-4007c411b743.jpg)

**Comment by younesaassila** [comment]
@triplesevenbob Still nothing, weird. TTV LOL PRO's log messages start with "[TTV LOL PRO]". The errors in your console seem to be related to uBlock. Have you configured VAFT properly? You could also try to reset uBlock settings to their default values, perhaps that would help.
