### ISSUE TITLE
Package is invalid: 'CRX_REQUIRED-PROOF-MISSING'.

### ISSUE THREAD

**Issue by Jawman2000** [younesaassila/ttv-lol-pro#71]
When I try to install the .crx file for edge this message "Package is invalid: 'CRZ_REQUIRED-PROOF-MISSING'." pops up at the top of my window.

**Comment by younesaassila** [comment]
You have to right-click, save link as… the file, like explained in the instruction guide [here](https://github.com/younesaassila/ttv-lol-pro/blob/main/README.md#-with-automatic-updates-windows--linux)
