### ISSUE TITLE
Unrecognized manifest key 'browser_specific_settings'.

### ISSUE THREAD

**Issue by MirTeiwaz** [younesaassila/ttv-lol-pro#72]
<img width="661" alt="Screenshot 2023-01-29 at 11 58 07" src="https://user-images.githubusercontent.com/16748184/215338632-38e2aced-06dd-4703-898d-63e63f0d0ee9.png">

What I see after installing the unpacked extension for Mac Chrome.

OS: macOS 13.1 Ventura
Browser: Chrome 110.0.5481.52 (Official Build) beta

**Comment by younesaassila** [comment]
That's just a warning, it can safely be ignored.
