### ISSUE TITLE
Could not load stream

### ISSUE THREAD

**Issue by Lucas559-noob** [younesaassila/ttv-lol-pro#74]
I tried to watch [this channel](https://www.twitch.tv/casimito), but the stream shows a error 
![image](https://user-images.githubusercontent.com/54007604/216156749-96172404-b7c5-448e-90a3-153025d7fdef.png)
is it geoblocked?

**Comment by younesaassila** [comment]
Yes this stream is geoblocked. Even without the extension, I cannot watch it from my region. You have no choice but to whitelist this channel and be in the correct region to watch their stream.
