### ISSUE TITLE
Should "Reset player on midroll" be disabled for whitelisted channels?

### ISSUE THREAD

**Issue by younesaassila** [younesaassila/ttv-lol-pro#80]
I'm wondering if the "Reset player" feature should be disabled if the channel is whitelisted.

- Some viewers might want to support a creator by watching ads on their channel
- Some viewers just use the Whitelist feature to watch geoblocked streams.

I can add a toggle option in settings to fix this but not sure what it should default to.
What are your thoughts on this?

**Comment by erik9012** [comment]
For whitelisted channels please disable it by default. A toggle to enable it would be cool

**Comment by younesaassila** [comment]
Closing since the "Reset player on midroll" feature is now deprecated.
