### ISSUE TITLE
Incorrect volume after player reset

### ISSUE THREAD

**Issue by younesaassila** [younesaassila/ttv-lol-pro#81]
I've read at least 2 reports of the player volume being incorrect (too low) after a reset. I haven't been able to reproduce the bug. Is anyone able to reproduce this bug consistently?

Is it linked to another extension? Is it due to the stream page being loaded directly (as in the user went to twitch.tv/channel directly without using the Twitch homepage)?

**Comment by younesaassila** [comment]
Edit: Volume slider still shows 100% after glitch, so likely this is the HTML video element not having its volume set correctly.

**Comment by DaveKap** [comment]
It's possible this is related to people using FFZ's audio compressor, which can disable when ad is blocked, thus making the stream quieter.

**Comment by younesaassila** [comment]
Removed help wanted label since haven't gotten a report of this bug in over two months
