### ISSUE TITLE
Still getting ads(kiwi browser so that could be the issue)

### ISSUE THREAD

**Issue by erik9012** [younesaassila/ttv-lol-pro#83]
Hello, im on phone. Would it be possible to block ads in kiwi browser? I still get ads. Is this expected or not?
![Screenshot_2023-02-10-11-58-26-608_com kiwibrowser browser](https://user-images.githubusercontent.com/57501353/218076130-e35df0fb-0d29-4bd4-92c3-09e57012e7fe.jpg)
![Screenshot_2023-02-10-11-57-34-784_com kiwibrowser browser](https://user-images.githubusercontent.com/57501353/218076138-36834263-05fe-4601-9c61-7d36fdc6eaa2.jpg)
![Screenshot_2023-02-10-11-57-18-844-edit_com kiwibrowser browser](https://user-images.githubusercontent.com/57501353/218076144-28f25b91-f98d-4525-a7d2-df2d70114c82.jpg)
![Screenshot_2023-02-10-11-57-08-808-edit_com kiwibrowser browser](https://user-images.githubusercontent.com/57501353/218076147-f24cb4aa-5b31-4fc9-ae83-146cf89080a9.jpg)
![Screenshot_2023-02-10-12-01-43-696-edit_com kiwibrowser browser](https://user-images.githubusercontent.com/57501353/218076258-31f547d4-8a46-4bdc-90e7-6e427eec9c8d.jpg)
It can also be that i do something wrong. In that case please tell me

**Comment by younesaassila** [comment]
I've never tried the extension on mobile. It's entirely possible there's bugs in there.

I'll look into it!

**Comment by erik9012** [comment]
Cool. Tanks a lot

**Comment by younesaassila** [comment]
The content script is not running because the `m.twitch.tv` website is not in the manifest host permissions. Should be an easy fix.
I still need to check if the reset player feature works on mobile.

I'll check and fix this in the coming days

**Comment by younesaassila** [comment]
Added basic mobile support in v1.8.1 (without "Reset player on midroll" feature since the Twitch mobile website is very different from the desktop site, requiring a lot of rewrite and experimentation)

**Comment by erik9012** [comment]
Thanks
