### ISSUE TITLE
Unable to use Picture in Picture mode when using Firefox

### ISSUE THREAD

**Issue by QuickStick123** [younesaassila/ttv-lol-pro#85]
https://github.com/TTV-LOL/extensions/issues/57

**Comment by younesaassila** [comment]
I don't think this is related to the extension since all it does is redirect the initial HLS master manifest request. HTTP streaming is not messed with. I'll check if it's working for me later, I'll keep you updated.

**Comment by younesaassila** [comment]
Yep not linked to the extension. I can enable PiP perfectly fine on Firefox.

**Comment by QuickStick123** [comment]
The issue is the twitch extensions seems to break this and was why I got confused when comparing.
