### ISSUE TITLE
"Managed by your organization" in Chrome menu after using allowlist reg.

### ISSUE THREAD

**Issue by DaveKap** [younesaassila/ttv-lol-pro#86]
This is less of a "this needs fixing" (since there is a way to make this display go away) and more of a "is this intended? does it have to do this?" kind of issue. Essentially, after adding the allowlist registry edit, Chrome now things it's being managed by an organization, which means this message appears below "exit" in Chrome's menu. When this message is clicked, it goes to a page which say "Your browser is managed. Your administrator can change your browser setup remotely. Activity on this device may also be managed outside of Chrome."

This is a little scary but I assume this is normal. Can I get a confirmation?

**Comment by younesaassila** [comment]
Yup this message is displayed by Chrome if any registry key related to Chrome is added. It sounds scary but simply adding a registry key doesn't mean someone can change your browser setup remotely. You have to be a part of the same network for that.

The sole reason why I'm using this registry editing trick is that the Chrome Web Store won't allow new Manifest v2 extensions, so we have to use this stupid workaround. Even then, browsers like Firefox allow extensions installed from sources other than its own store but Chrome being Chrome they want everyone to use their Google store in the name of "security" (even though half of the Chrome Web Store extensions are scams/malware).

You do make a good point though and I'll think about adding a notice in the README that this method displays scary messages.
