### ISSUE TITLE
Background tabs not loading

### ISSUE THREAD

**Issue by graphicjazz** [younesaassila/ttv-lol-pro#87]
When I have this extension enabled, and when I used to have the original TTV LOL, Twitch streams in the background will not load. Only when bringing the tab to the foreground will the stream start to play.

**Comment by younesaassila** [comment]
Were you using TTV LOL and TTV LOL PRO simultaneously?

**Comment by graphicjazz** [comment]
No, only one at a time. Currently I only have the TTV LOL PRO extension installed. I uninstalled TTV LOL before installing TTV LOL PRO.

**Comment by younesaassila** [comment]
What browser are you using? Does disabling the extension fix your problem?

**Comment by graphicjazz** [comment]
I have noticed the issue in both Chrome and Firefox. Disabling the extension does fix it. Are you unable to replicate the issue?

**Comment by younesaassila** [comment]
Can you describe the steps to reproduce the issue?

What I've tested is opening a Twitch link in a new background tab, but with or without the extension the stream doesn't start playing until I click the newly opened tab.

**Comment by graphicjazz** [comment]
So after some additional testing I have found that Twitch no longer loads in the background at all. I had originally tested this a while ago so I'm not sure if a browser update or a Twitch update changed this behavior. Closing this issue as it is not related to this extension anymore.
