### ISSUE TITLE
a proxy or unblocker has been detected. 

### ISSUE THREAD

**Issue by DcSensai** [younesaassila/ttv-lol-pro#91]
tried to watch channel "tokushoutsu" and got this even after turning off adnauseum and ublock origin.  
![tokushoutsu](https://user-images.githubusercontent.com/61247916/220149958-5dc49aa1-b73b-4a73-8ccc-915e5d0690ca.png)

**Comment by younesaassila** [comment]
Yes some streams are geoblocked. You can only watch them if you're in an allowed country. If you are, you can whitelist the channel in TTV LOL PRO's popup menu.
