### ISSUE TITLE
TTV LOL PRO not working on Player pages?

### ISSUE THREAD

**Issue by TsukiZero** [younesaassila/ttv-lol-pro#95]
More specifically the ones that starts with `https://player.twitch.tv/?channel=`

**Comment by HackerPide** [comment]
https://github.com/younesaassila/ttv-lol-pro/discussions/94#discussioncomment-5108869

**Comment by younesaassila** [comment]
Yes, the add-on doesn't currently have the permissions for `player.twitch.tv` and `embed.twitch.tv`
