### ISSUE TITLE
TTV LOL extension showing Twitch streamers as offline (they are not)

### ISSUE THREAD

**Issue by Makezu90** [younesaassila/ttv-lol-pro#97]
Title.

When i refresh site it works again but after few minutes same issue. When i disabled extension it works normally so its extension issue. fix it.

![opera_MGlqgyzqZI](https://user-images.githubusercontent.com/89158176/221518542-df6bac10-eb27-4f18-8bab-0929c46487c5.jpg)

**Comment by younesaassila** [comment]
Are you using VAFT with TTV LOL PRO?
I know I had the same issue occasionally but not frequently enough to bother me.

Is it happening every time you watch a stream?

**Comment by younesaassila** [comment]
If you aren't using VAFT, try turning off "Reset player on midroll" in TTV LOL PRO's options (On Chrome right-click icon > Options, on Firefox `about:addons` > TTV LOL PRO > ••• > Preferences)

**Comment by Makezu90** [comment]
what is that VAFT? i have no any other adblocks on twitch right now only that TTV LOL PRO and not use chrome, i use opera. It was turned off when that happened. Now i tried turn on it again atleast now it works normally.. So not sure why that happens sometimes.
